// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _calculateForState_HH_
#define _calculateForState_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "calculateDistanceFor.h"

namespace ap_rtl {

struct calculateForState : public sc_module {
    // Port declarations 60
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_in< sc_lv<1> > p_read;
    sc_in< sc_lv<1> > p_read1;
    sc_in< sc_lv<8> > p_read2;
    sc_in< sc_lv<8> > p_read3;
    sc_in< sc_lv<8> > p_read4;
    sc_in< sc_lv<8> > p_read5;
    sc_in< sc_lv<8> > p_read6;
    sc_in< sc_lv<8> > p_read7;
    sc_in< sc_lv<8> > p_read8;
    sc_in< sc_lv<8> > p_read9;
    sc_in< sc_lv<8> > p_read10;
    sc_in< sc_lv<8> > p_read11;
    sc_in< sc_lv<8> > p_read12;
    sc_in< sc_lv<8> > p_read13;
    sc_in< sc_lv<8> > p_read14;
    sc_in< sc_lv<8> > p_read15;
    sc_in< sc_lv<8> > p_read16;
    sc_in< sc_lv<8> > p_read17;
    sc_in< sc_lv<8> > p_read18;
    sc_in< sc_lv<8> > p_read31;
    sc_in< sc_lv<8> > p_read32;
    sc_in< sc_lv<8> > p_read33;
    sc_in< sc_lv<8> > p_read34;
    sc_in< sc_lv<8> > p_read35;
    sc_in< sc_lv<8> > p_read36;
    sc_in< sc_lv<8> > p_read37;
    sc_out< sc_lv<3> > HammingTable_hammingDistances_finalStates_address0;
    sc_out< sc_logic > HammingTable_hammingDistances_finalStates_ce0;
    sc_out< sc_logic > HammingTable_hammingDistances_finalStates_we0;
    sc_out< sc_lv<8> > HammingTable_hammingDistances_finalStates_d0;
    sc_in< sc_lv<8> > HammingTable_hammingDistances_finalStates_q0;
    sc_out< sc_lv<3> > HammingTable_hammingDistances_finalStates_address1;
    sc_out< sc_logic > HammingTable_hammingDistances_finalStates_ce1;
    sc_out< sc_logic > HammingTable_hammingDistances_finalStates_we1;
    sc_out< sc_lv<8> > HammingTable_hammingDistances_finalStates_d1;
    sc_in< sc_lv<8> > HammingTable_hammingDistances_finalStates_q1;
    sc_in< sc_lv<5> > state;
    sc_out< sc_lv<8> > ap_return_0;
    sc_out< sc_lv<8> > ap_return_1;
    sc_out< sc_lv<8> > ap_return_2;
    sc_out< sc_lv<8> > ap_return_3;
    sc_out< sc_lv<8> > ap_return_4;
    sc_out< sc_lv<8> > ap_return_5;
    sc_out< sc_lv<8> > ap_return_6;
    sc_out< sc_lv<8> > ap_return_7;
    sc_out< sc_lv<8> > ap_return_8;
    sc_out< sc_lv<8> > ap_return_9;
    sc_out< sc_lv<8> > ap_return_10;
    sc_out< sc_lv<8> > ap_return_11;
    sc_out< sc_lv<8> > ap_return_12;
    sc_out< sc_lv<8> > ap_return_13;
    sc_out< sc_lv<8> > ap_return_14;
    sc_out< sc_lv<8> > ap_return_15;
    sc_in< sc_logic > ap_ce;


    // Module declarations
    calculateForState(sc_module_name name);
    SC_HAS_PROCESS(calculateForState);

    ~calculateForState();

    sc_trace_file* mVcdFile;

    calculateDistanceFor* grp_calculateDistanceFor_fu_1033;
    calculateDistanceFor* grp_calculateDistanceFor_fu_1047;
    sc_signal< sc_lv<2> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state1;
    sc_signal< sc_lv<8> > grp_calculateDistanceFor_fu_1033_ap_return;
    sc_signal< sc_lv<8> > reg_1081;
    sc_signal< sc_lv<5> > state_read_read_fu_118_p2;
    sc_signal< sc_lv<8> > grp_calculateDistanceFor_fu_1047_ap_return;
    sc_signal< sc_lv<8> > reg_1094;
    sc_signal< sc_lv<5> > state_read_reg_1215;
    sc_signal< sc_lv<8> > p_read_26_reg_1219;
    sc_signal< sc_lv<8> > p_read_27_reg_1234;
    sc_signal< sc_lv<8> > p_read_28_reg_1249;
    sc_signal< sc_lv<8> > p_read_29_reg_1264;
    sc_signal< sc_lv<8> > p_read_30_reg_1279;
    sc_signal< sc_lv<8> > p_read_31_reg_1294;
    sc_signal< sc_lv<8> > p_read_32_reg_1309;
    sc_signal< sc_lv<8> > p_read1029_reg_1324;
    sc_signal< sc_lv<8> > p_read928_reg_1339;
    sc_signal< sc_lv<8> > p_read827_reg_1354;
    sc_signal< sc_lv<8> > p_read726_reg_1369;
    sc_signal< sc_lv<8> > p_read625_reg_1384;
    sc_signal< sc_lv<8> > p_read524_reg_1399;
    sc_signal< sc_lv<8> > p_read423_reg_1414;
    sc_signal< sc_lv<8> > p_read322_reg_1429;
    sc_signal< sc_lv<8> > p_read221_reg_1444;
    sc_signal< sc_lv<3> > HammingTable_hamming_61_reg_1459;
    sc_signal< sc_lv<3> > HammingTable_hamming_63_reg_1464;
    sc_signal< sc_lv<3> > HammingTable_hamming_55_reg_1469;
    sc_signal< sc_lv<3> > HammingTable_hamming_57_reg_1474;
    sc_signal< sc_lv<3> > HammingTable_hamming_49_reg_1479;
    sc_signal< sc_lv<3> > HammingTable_hamming_51_reg_1484;
    sc_signal< sc_lv<3> > HammingTable_hamming_43_reg_1489;
    sc_signal< sc_lv<3> > HammingTable_hamming_45_reg_1494;
    sc_signal< sc_logic > grp_calculateDistanceFor_fu_1033_ap_ready;
    sc_signal< sc_logic > grp_calculateDistanceFor_fu_1033_firstBit;
    sc_signal< sc_logic > grp_calculateDistanceFor_fu_1033_secondBit;
    sc_signal< sc_lv<8> > grp_calculateDistanceFor_fu_1033_previousDistance;
    sc_signal< sc_logic > grp_calculateDistanceFor_fu_1047_ap_ready;
    sc_signal< sc_logic > grp_calculateDistanceFor_fu_1047_firstBit;
    sc_signal< sc_logic > grp_calculateDistanceFor_fu_1047_secondBit;
    sc_signal< sc_lv<8> > grp_calculateDistanceFor_fu_1047_previousDistance;
    sc_signal< sc_lv<8> > ap_phi_mux_HammingTable_gTransi_phi_fu_436_p4;
    sc_signal< sc_logic > ap_CS_fsm_state2;
    sc_signal< sc_lv<1> > grp_fu_1107_p2;
    sc_signal< sc_lv<8> > ap_phi_mux_HammingTable_hTransi_phi_fu_446_p4;
    sc_signal< sc_lv<8> > ap_phi_mux_HammingTable_eTransi_phi_fu_456_p4;
    sc_signal< sc_lv<8> > ap_phi_mux_HammingTable_fTransi_phi_fu_466_p4;
    sc_signal< sc_lv<8> > ap_phi_mux_HammingTable_cTransi_phi_fu_476_p4;
    sc_signal< sc_lv<8> > ap_phi_mux_HammingTable_dTransi_phi_fu_486_p4;
    sc_signal< sc_lv<8> > ap_phi_mux_HammingTable_bTransi_phi_fu_496_p4;
    sc_signal< sc_lv<8> > ap_phi_mux_HammingTable_aTransi_phi_fu_506_p4;
    sc_signal< sc_lv<8> > ap_phi_mux_HammingTable_cTransi_30_phi_fu_516_p26;
    sc_signal< sc_lv<8> > HammingTable_cTransi_30_reg_513;
    sc_signal< sc_lv<1> > grp_fu_1113_p2;
    sc_signal< sc_lv<8> > ap_phi_mux_phi_ln228_phi_fu_549_p26;
    sc_signal< sc_lv<8> > phi_ln228_reg_546;
    sc_signal< sc_lv<8> > ap_phi_mux_HammingTable_dTransi_20_phi_fu_581_p26;
    sc_signal< sc_lv<8> > HammingTable_dTransi_20_reg_578;
    sc_signal< sc_lv<8> > ap_phi_mux_phi_ln228_1_phi_fu_614_p26;
    sc_signal< sc_lv<8> > phi_ln228_1_reg_611;
    sc_signal< sc_lv<8> > ap_phi_mux_phi_ln228_2_phi_fu_646_p26;
    sc_signal< sc_lv<8> > phi_ln228_2_reg_643;
    sc_signal< sc_lv<8> > ap_phi_mux_HammingTable_eTransi_30_phi_fu_678_p26;
    sc_signal< sc_lv<8> > HammingTable_eTransi_30_reg_675;
    sc_signal< sc_lv<8> > ap_phi_mux_phi_ln228_3_phi_fu_711_p26;
    sc_signal< sc_lv<8> > phi_ln228_3_reg_708;
    sc_signal< sc_lv<8> > ap_phi_mux_HammingTable_bTransi_20_phi_fu_743_p26;
    sc_signal< sc_lv<8> > HammingTable_bTransi_20_reg_740;
    sc_signal< sc_lv<8> > ap_phi_mux_HammingTable_fTransi_20_phi_fu_776_p26;
    sc_signal< sc_lv<8> > HammingTable_fTransi_20_reg_773;
    sc_signal< sc_lv<8> > ap_phi_mux_phi_ln228_4_phi_fu_809_p26;
    sc_signal< sc_lv<8> > phi_ln228_4_reg_806;
    sc_signal< sc_lv<8> > ap_phi_mux_HammingTable_gTransi_30_phi_fu_841_p26;
    sc_signal< sc_lv<8> > HammingTable_gTransi_30_reg_838;
    sc_signal< sc_lv<8> > ap_phi_mux_phi_ln228_5_phi_fu_874_p26;
    sc_signal< sc_lv<8> > phi_ln228_5_reg_871;
    sc_signal< sc_lv<8> > ap_phi_mux_phi_ln228_6_phi_fu_906_p26;
    sc_signal< sc_lv<8> > phi_ln228_6_reg_903;
    sc_signal< sc_lv<8> > ap_phi_mux_HammingTable_hTransi_20_phi_fu_938_p26;
    sc_signal< sc_lv<8> > HammingTable_hTransi_20_reg_935;
    sc_signal< sc_lv<8> > ap_phi_mux_phi_ln228_7_phi_fu_971_p26;
    sc_signal< sc_lv<8> > phi_ln228_7_reg_968;
    sc_signal< sc_lv<8> > ap_phi_mux_HammingTable_aTransi_30_phi_fu_1003_p26;
    sc_signal< sc_lv<8> > HammingTable_aTransi_30_reg_1000;
    sc_signal< sc_lv<3> > HammingTable_hamming_59_gep_fu_307_p3;
    sc_signal< sc_lv<3> > HammingTable_hamming_60_gep_fu_316_p3;
    sc_signal< sc_lv<3> > HammingTable_hamming_53_gep_fu_343_p3;
    sc_signal< sc_lv<3> > HammingTable_hamming_54_gep_fu_352_p3;
    sc_signal< sc_lv<3> > HammingTable_hamming_47_gep_fu_379_p3;
    sc_signal< sc_lv<3> > HammingTable_hamming_48_gep_fu_388_p3;
    sc_signal< sc_lv<3> > HammingTable_hamming_gep_fu_415_p3;
    sc_signal< sc_lv<3> > HammingTable_hamming_42_gep_fu_424_p3;
    sc_signal< sc_lv<2> > ap_NS_fsm;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<2> ap_ST_fsm_state1;
    static const sc_lv<2> ap_ST_fsm_state2;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<5> ap_const_lv5_7;
    static const sc_lv<5> ap_const_lv5_6;
    static const sc_lv<5> ap_const_lv5_5;
    static const sc_lv<5> ap_const_lv5_4;
    static const sc_lv<5> ap_const_lv5_3;
    static const sc_lv<5> ap_const_lv5_2;
    static const sc_lv<5> ap_const_lv5_1;
    static const sc_lv<5> ap_const_lv5_0;
    static const sc_lv<8> ap_const_lv8_FF;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<64> ap_const_lv64_3;
    static const sc_lv<64> ap_const_lv64_7;
    static const sc_lv<64> ap_const_lv64_2;
    static const sc_lv<64> ap_const_lv64_6;
    static const sc_lv<64> ap_const_lv64_1;
    static const sc_lv<64> ap_const_lv64_5;
    static const sc_lv<64> ap_const_lv64_0;
    static const sc_lv<64> ap_const_lv64_4;
    static const bool ap_const_boolean_1;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_HammingTable_hammingDistances_finalStates_address0();
    void thread_HammingTable_hammingDistances_finalStates_address1();
    void thread_HammingTable_hammingDistances_finalStates_ce0();
    void thread_HammingTable_hammingDistances_finalStates_ce1();
    void thread_HammingTable_hammingDistances_finalStates_d0();
    void thread_HammingTable_hammingDistances_finalStates_d1();
    void thread_HammingTable_hammingDistances_finalStates_we0();
    void thread_HammingTable_hammingDistances_finalStates_we1();
    void thread_HammingTable_hamming_42_gep_fu_424_p3();
    void thread_HammingTable_hamming_43_reg_1489();
    void thread_HammingTable_hamming_45_reg_1494();
    void thread_HammingTable_hamming_47_gep_fu_379_p3();
    void thread_HammingTable_hamming_48_gep_fu_388_p3();
    void thread_HammingTable_hamming_49_reg_1479();
    void thread_HammingTable_hamming_51_reg_1484();
    void thread_HammingTable_hamming_53_gep_fu_343_p3();
    void thread_HammingTable_hamming_54_gep_fu_352_p3();
    void thread_HammingTable_hamming_55_reg_1469();
    void thread_HammingTable_hamming_57_reg_1474();
    void thread_HammingTable_hamming_59_gep_fu_307_p3();
    void thread_HammingTable_hamming_60_gep_fu_316_p3();
    void thread_HammingTable_hamming_61_reg_1459();
    void thread_HammingTable_hamming_63_reg_1464();
    void thread_HammingTable_hamming_gep_fu_415_p3();
    void thread_ap_CS_fsm_state1();
    void thread_ap_CS_fsm_state2();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_phi_mux_HammingTable_aTransi_30_phi_fu_1003_p26();
    void thread_ap_phi_mux_HammingTable_aTransi_phi_fu_506_p4();
    void thread_ap_phi_mux_HammingTable_bTransi_20_phi_fu_743_p26();
    void thread_ap_phi_mux_HammingTable_bTransi_phi_fu_496_p4();
    void thread_ap_phi_mux_HammingTable_cTransi_30_phi_fu_516_p26();
    void thread_ap_phi_mux_HammingTable_cTransi_phi_fu_476_p4();
    void thread_ap_phi_mux_HammingTable_dTransi_20_phi_fu_581_p26();
    void thread_ap_phi_mux_HammingTable_dTransi_phi_fu_486_p4();
    void thread_ap_phi_mux_HammingTable_eTransi_30_phi_fu_678_p26();
    void thread_ap_phi_mux_HammingTable_eTransi_phi_fu_456_p4();
    void thread_ap_phi_mux_HammingTable_fTransi_20_phi_fu_776_p26();
    void thread_ap_phi_mux_HammingTable_fTransi_phi_fu_466_p4();
    void thread_ap_phi_mux_HammingTable_gTransi_30_phi_fu_841_p26();
    void thread_ap_phi_mux_HammingTable_gTransi_phi_fu_436_p4();
    void thread_ap_phi_mux_HammingTable_hTransi_20_phi_fu_938_p26();
    void thread_ap_phi_mux_HammingTable_hTransi_phi_fu_446_p4();
    void thread_ap_phi_mux_phi_ln228_1_phi_fu_614_p26();
    void thread_ap_phi_mux_phi_ln228_2_phi_fu_646_p26();
    void thread_ap_phi_mux_phi_ln228_3_phi_fu_711_p26();
    void thread_ap_phi_mux_phi_ln228_4_phi_fu_809_p26();
    void thread_ap_phi_mux_phi_ln228_5_phi_fu_874_p26();
    void thread_ap_phi_mux_phi_ln228_6_phi_fu_906_p26();
    void thread_ap_phi_mux_phi_ln228_7_phi_fu_971_p26();
    void thread_ap_phi_mux_phi_ln228_phi_fu_549_p26();
    void thread_ap_ready();
    void thread_ap_return_0();
    void thread_ap_return_1();
    void thread_ap_return_10();
    void thread_ap_return_11();
    void thread_ap_return_12();
    void thread_ap_return_13();
    void thread_ap_return_14();
    void thread_ap_return_15();
    void thread_ap_return_2();
    void thread_ap_return_3();
    void thread_ap_return_4();
    void thread_ap_return_5();
    void thread_ap_return_6();
    void thread_ap_return_7();
    void thread_ap_return_8();
    void thread_ap_return_9();
    void thread_grp_calculateDistanceFor_fu_1033_firstBit();
    void thread_grp_calculateDistanceFor_fu_1033_previousDistance();
    void thread_grp_calculateDistanceFor_fu_1033_secondBit();
    void thread_grp_calculateDistanceFor_fu_1047_firstBit();
    void thread_grp_calculateDistanceFor_fu_1047_previousDistance();
    void thread_grp_calculateDistanceFor_fu_1047_secondBit();
    void thread_grp_fu_1107_p2();
    void thread_grp_fu_1113_p2();
    void thread_state_read_read_fu_118_p2();
    void thread_ap_NS_fsm();
};

}

using namespace ap_rtl;

#endif
