create_clock -period 20.000 -name clk -waveform {0.000 10.000} [get_ports clk]

set_property IOSTANDARD LVCMOS33 [get_ports {dat[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dat[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dat[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dat[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dat[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dat[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dat[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dat[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dat[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dat[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dat[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dat[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dat[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dat[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {out[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {out[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {out[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {out[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {out[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {out[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {out[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports ready]
set_property IOSTANDARD LVCMOS33 [get_ports reset]
set_property PULLDOWN true [get_ports clk]
set_property PULLDOWN true [get_ports ready]
set_property PULLDOWN true [get_ports reset]
set_property SLEW SLOW [get_ports {out[6]}]
set_property SLEW SLOW [get_ports {out[5]}]
set_property SLEW SLOW [get_ports {out[4]}]
set_property SLEW SLOW [get_ports {out[3]}]
set_property SLEW SLOW [get_ports {out[2]}]
set_property SLEW SLOW [get_ports {out[1]}]
set_property SLEW SLOW [get_ports {out[0]}]

set_output_delay -clock clk 1.000 out
set_input_delay -clock clk -max 0.100 [list [get_ports -regexp -filter { NAME =~  ".*dat.*" && DIRECTION == "IN" }] [get_ports -regexp -filter { NAME =~  ".*reset.*" && DIRECTION == "IN" }] [get_ports -regexp -filter { NAME =~  ".*ready.*" && DIRECTION == "IN" }]]

set_property PACKAGE_PIN AE21 [get_ports reset]
set_property PACKAGE_PIN AB21 [get_ports clk]
set_property PACKAGE_PIN AC18 [get_ports ready]
set_property PACKAGE_PIN AC17 [get_ports {dat[11]}]
set_property PACKAGE_PIN AB17 [get_ports {dat[12]}]
set_property PACKAGE_PIN AD18 [get_ports {dat[13]}]
set_property PACKAGE_PIN AF17 [get_ports {dat[10]}]
set_property PACKAGE_PIN AF18 [get_ports {dat[9]}]
set_property PACKAGE_PIN AF15 [get_ports {dat[1]}]
set_property PACKAGE_PIN AE20 [get_ports {out[6]}]
set_property PACKAGE_PIN AC19 [get_ports {out[2]}]
set_property PACKAGE_PIN AC16 [get_ports {dat[8]}]
set_property PACKAGE_PIN AE17 [get_ports {dat[0]}]
set_property PACKAGE_PIN AF20 [get_ports {out[5]}]
set_property PACKAGE_PIN AF19 [get_ports {out[3]}]
set_property PACKAGE_PIN AD16 [get_ports {dat[7]}]
set_property PACKAGE_PIN AA17 [get_ports {dat[6]}]
set_property PACKAGE_PIN AE16 [get_ports {dat[3]}]
set_property PACKAGE_PIN AE15 [get_ports {dat[2]}]
set_property PACKAGE_PIN AE18 [get_ports {out[4]}]
set_property PACKAGE_PIN AA18 [get_ports {dat[5]}]
set_property PACKAGE_PIN AD15 [get_ports {dat[4]}]
set_property PACKAGE_PIN AD20 [get_ports {out[0]}]
set_property PACKAGE_PIN AD19 [get_ports {out[1]}]

