// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module calculateForState (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        p_read,
        p_read1,
        p_read2,
        p_read3,
        p_read4,
        p_read5,
        p_read6,
        p_read7,
        p_read8,
        p_read9,
        p_read10,
        p_read11,
        p_read12,
        p_read13,
        p_read14,
        p_read15,
        p_read16,
        p_read17,
        p_read18,
        p_read31,
        p_read32,
        p_read33,
        p_read34,
        p_read35,
        p_read36,
        p_read37,
        HammingTable_hammingDistances_finalStates_address0,
        HammingTable_hammingDistances_finalStates_ce0,
        HammingTable_hammingDistances_finalStates_we0,
        HammingTable_hammingDistances_finalStates_d0,
        HammingTable_hammingDistances_finalStates_q0,
        HammingTable_hammingDistances_finalStates_address1,
        HammingTable_hammingDistances_finalStates_ce1,
        HammingTable_hammingDistances_finalStates_we1,
        HammingTable_hammingDistances_finalStates_d1,
        HammingTable_hammingDistances_finalStates_q1,
        state,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3,
        ap_return_4,
        ap_return_5,
        ap_return_6,
        ap_return_7,
        ap_return_8,
        ap_return_9,
        ap_return_10,
        ap_return_11,
        ap_return_12,
        ap_return_13,
        ap_return_14,
        ap_return_15,
        ap_ce
);

parameter    ap_ST_fsm_state1 = 2'd1;
parameter    ap_ST_fsm_state2 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [0:0] p_read;
input  [0:0] p_read1;
input  [7:0] p_read2;
input  [7:0] p_read3;
input  [7:0] p_read4;
input  [7:0] p_read5;
input  [7:0] p_read6;
input  [7:0] p_read7;
input  [7:0] p_read8;
input  [7:0] p_read9;
input  [7:0] p_read10;
input  [7:0] p_read11;
input  [7:0] p_read12;
input  [7:0] p_read13;
input  [7:0] p_read14;
input  [7:0] p_read15;
input  [7:0] p_read16;
input  [7:0] p_read17;
input  [7:0] p_read18;
input  [7:0] p_read31;
input  [7:0] p_read32;
input  [7:0] p_read33;
input  [7:0] p_read34;
input  [7:0] p_read35;
input  [7:0] p_read36;
input  [7:0] p_read37;
output  [2:0] HammingTable_hammingDistances_finalStates_address0;
output   HammingTable_hammingDistances_finalStates_ce0;
output   HammingTable_hammingDistances_finalStates_we0;
output  [7:0] HammingTable_hammingDistances_finalStates_d0;
input  [7:0] HammingTable_hammingDistances_finalStates_q0;
output  [2:0] HammingTable_hammingDistances_finalStates_address1;
output   HammingTable_hammingDistances_finalStates_ce1;
output   HammingTable_hammingDistances_finalStates_we1;
output  [7:0] HammingTable_hammingDistances_finalStates_d1;
input  [7:0] HammingTable_hammingDistances_finalStates_q1;
input  [4:0] state;
output  [7:0] ap_return_0;
output  [7:0] ap_return_1;
output  [7:0] ap_return_2;
output  [7:0] ap_return_3;
output  [7:0] ap_return_4;
output  [7:0] ap_return_5;
output  [7:0] ap_return_6;
output  [7:0] ap_return_7;
output  [7:0] ap_return_8;
output  [7:0] ap_return_9;
output  [7:0] ap_return_10;
output  [7:0] ap_return_11;
output  [7:0] ap_return_12;
output  [7:0] ap_return_13;
output  [7:0] ap_return_14;
output  [7:0] ap_return_15;
input   ap_ce;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[2:0] HammingTable_hammingDistances_finalStates_address0;
reg HammingTable_hammingDistances_finalStates_ce0;
reg HammingTable_hammingDistances_finalStates_we0;
reg[7:0] HammingTable_hammingDistances_finalStates_d0;
reg[2:0] HammingTable_hammingDistances_finalStates_address1;
reg HammingTable_hammingDistances_finalStates_ce1;
reg HammingTable_hammingDistances_finalStates_we1;
reg[7:0] HammingTable_hammingDistances_finalStates_d1;

(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [7:0] grp_calculateDistanceFor_fu_1033_ap_return;
reg   [7:0] reg_1081;
wire   [4:0] state_read_read_fu_118_p2;
wire   [7:0] grp_calculateDistanceFor_fu_1047_ap_return;
reg   [7:0] reg_1094;
reg   [4:0] state_read_reg_1215;
reg   [7:0] p_read_26_reg_1219;
reg   [7:0] p_read_27_reg_1234;
reg   [7:0] p_read_28_reg_1249;
reg   [7:0] p_read_29_reg_1264;
reg   [7:0] p_read_30_reg_1279;
reg   [7:0] p_read_31_reg_1294;
reg   [7:0] p_read_32_reg_1309;
reg   [7:0] p_read1029_reg_1324;
reg   [7:0] p_read928_reg_1339;
reg   [7:0] p_read827_reg_1354;
reg   [7:0] p_read726_reg_1369;
reg   [7:0] p_read625_reg_1384;
reg   [7:0] p_read524_reg_1399;
reg   [7:0] p_read423_reg_1414;
reg   [7:0] p_read322_reg_1429;
reg   [7:0] p_read221_reg_1444;
wire   [2:0] HammingTable_hamming_61_reg_1459;
wire   [2:0] HammingTable_hamming_63_reg_1464;
wire   [2:0] HammingTable_hamming_55_reg_1469;
wire   [2:0] HammingTable_hamming_57_reg_1474;
wire   [2:0] HammingTable_hamming_49_reg_1479;
wire   [2:0] HammingTable_hamming_51_reg_1484;
wire   [2:0] HammingTable_hamming_43_reg_1489;
wire   [2:0] HammingTable_hamming_45_reg_1494;
wire    grp_calculateDistanceFor_fu_1033_ap_ready;
reg    grp_calculateDistanceFor_fu_1033_firstBit;
reg    grp_calculateDistanceFor_fu_1033_secondBit;
reg   [7:0] grp_calculateDistanceFor_fu_1033_previousDistance;
wire    grp_calculateDistanceFor_fu_1047_ap_ready;
reg    grp_calculateDistanceFor_fu_1047_firstBit;
reg    grp_calculateDistanceFor_fu_1047_secondBit;
reg   [7:0] grp_calculateDistanceFor_fu_1047_previousDistance;
reg   [7:0] ap_phi_mux_HammingTable_gTransi_phi_fu_436_p4;
wire    ap_CS_fsm_state2;
wire   [0:0] grp_fu_1107_p2;
reg   [7:0] ap_phi_mux_HammingTable_hTransi_phi_fu_446_p4;
reg   [7:0] ap_phi_mux_HammingTable_eTransi_phi_fu_456_p4;
reg   [7:0] ap_phi_mux_HammingTable_fTransi_phi_fu_466_p4;
reg   [7:0] ap_phi_mux_HammingTable_cTransi_phi_fu_476_p4;
reg   [7:0] ap_phi_mux_HammingTable_dTransi_phi_fu_486_p4;
reg   [7:0] ap_phi_mux_HammingTable_bTransi_phi_fu_496_p4;
reg   [7:0] ap_phi_mux_HammingTable_aTransi_phi_fu_506_p4;
reg   [7:0] ap_phi_mux_HammingTable_cTransi_30_phi_fu_516_p26;
reg   [7:0] HammingTable_cTransi_30_reg_513;
wire   [0:0] grp_fu_1113_p2;
reg   [7:0] ap_phi_mux_phi_ln228_phi_fu_549_p26;
reg   [7:0] phi_ln228_reg_546;
reg   [7:0] ap_phi_mux_HammingTable_dTransi_20_phi_fu_581_p26;
reg   [7:0] HammingTable_dTransi_20_reg_578;
reg   [7:0] ap_phi_mux_phi_ln228_1_phi_fu_614_p26;
reg   [7:0] phi_ln228_1_reg_611;
reg   [7:0] ap_phi_mux_phi_ln228_2_phi_fu_646_p26;
reg   [7:0] phi_ln228_2_reg_643;
reg   [7:0] ap_phi_mux_HammingTable_eTransi_30_phi_fu_678_p26;
reg   [7:0] HammingTable_eTransi_30_reg_675;
reg   [7:0] ap_phi_mux_phi_ln228_3_phi_fu_711_p26;
reg   [7:0] phi_ln228_3_reg_708;
reg   [7:0] ap_phi_mux_HammingTable_bTransi_20_phi_fu_743_p26;
reg   [7:0] HammingTable_bTransi_20_reg_740;
reg   [7:0] ap_phi_mux_HammingTable_fTransi_20_phi_fu_776_p26;
reg   [7:0] HammingTable_fTransi_20_reg_773;
reg   [7:0] ap_phi_mux_phi_ln228_4_phi_fu_809_p26;
reg   [7:0] phi_ln228_4_reg_806;
reg   [7:0] ap_phi_mux_HammingTable_gTransi_30_phi_fu_841_p26;
reg   [7:0] HammingTable_gTransi_30_reg_838;
reg   [7:0] ap_phi_mux_phi_ln228_5_phi_fu_874_p26;
reg   [7:0] phi_ln228_5_reg_871;
reg   [7:0] ap_phi_mux_phi_ln228_6_phi_fu_906_p26;
reg   [7:0] phi_ln228_6_reg_903;
reg   [7:0] ap_phi_mux_HammingTable_hTransi_20_phi_fu_938_p26;
reg   [7:0] HammingTable_hTransi_20_reg_935;
reg   [7:0] ap_phi_mux_phi_ln228_7_phi_fu_971_p26;
reg   [7:0] phi_ln228_7_reg_968;
reg   [7:0] ap_phi_mux_HammingTable_aTransi_30_phi_fu_1003_p26;
reg   [7:0] HammingTable_aTransi_30_reg_1000;
wire   [2:0] HammingTable_hamming_59_gep_fu_307_p3;
wire   [2:0] HammingTable_hamming_60_gep_fu_316_p3;
wire   [2:0] HammingTable_hamming_53_gep_fu_343_p3;
wire   [2:0] HammingTable_hamming_54_gep_fu_352_p3;
wire   [2:0] HammingTable_hamming_47_gep_fu_379_p3;
wire   [2:0] HammingTable_hamming_48_gep_fu_388_p3;
wire   [2:0] HammingTable_hamming_gep_fu_415_p3;
wire   [2:0] HammingTable_hamming_42_gep_fu_424_p3;
reg   [1:0] ap_NS_fsm;

// power-on initialization
initial begin
#0 ap_CS_fsm = 2'd1;
end

calculateDistanceFor grp_calculateDistanceFor_fu_1033(
    .ap_ready(grp_calculateDistanceFor_fu_1033_ap_ready),
    .p_read(p_read),
    .p_read1(p_read1),
    .firstBit(grp_calculateDistanceFor_fu_1033_firstBit),
    .secondBit(grp_calculateDistanceFor_fu_1033_secondBit),
    .previousDistance(grp_calculateDistanceFor_fu_1033_previousDistance),
    .ap_return(grp_calculateDistanceFor_fu_1033_ap_return)
);

calculateDistanceFor grp_calculateDistanceFor_fu_1047(
    .ap_ready(grp_calculateDistanceFor_fu_1047_ap_ready),
    .p_read(p_read),
    .p_read1(p_read1),
    .firstBit(grp_calculateDistanceFor_fu_1047_firstBit),
    .secondBit(grp_calculateDistanceFor_fu_1047_secondBit),
    .previousDistance(grp_calculateDistanceFor_fu_1047_previousDistance),
    .ap_return(grp_calculateDistanceFor_fu_1047_ap_return)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2) & (grp_fu_1113_p2 == 1'd1) & (state_read_reg_1215 == 5'd3)) | ((1'b1 == ap_ce) & (grp_fu_1113_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2) & (state_read_reg_1215 == 5'd3)) | ((state_read_reg_1215 == 5'd5) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2) & (grp_fu_1113_p2 == 1'd1)) | ((state_read_reg_1215 == 5'd5) & (1'b1 == ap_ce) & (grp_fu_1113_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)) | ((state_read_reg_1215 == 5'd7) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2) & (grp_fu_1113_p2 == 1'd1)) | ((state_read_reg_1215 == 5'd7) & (1'b1 == ap_ce) & (grp_fu_1113_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)))) begin
        HammingTable_aTransi_30_reg_1000 <= p_read221_reg_1444;
    end else if ((((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2) & (grp_fu_1113_p2 == 1'd1) & (state_read_reg_1215 == 5'd1)) | ((1'b1 == ap_ce) & (grp_fu_1113_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2) & (state_read_reg_1215 == 5'd1)))) begin
        HammingTable_aTransi_30_reg_1000 <= ap_phi_mux_HammingTable_aTransi_phi_fu_506_p4;
    end else if (((state_read_read_fu_118_p2 == 5'd0) & (1'b1 == ap_ce) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        HammingTable_aTransi_30_reg_1000 <= grp_calculateDistanceFor_fu_1033_ap_return;
    end else if ((((state_read_read_fu_118_p2 == 5'd6) & (1'b1 == ap_ce) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)) | (~(state_read_read_fu_118_p2 == 5'd5) & ~(state_read_read_fu_118_p2 == 5'd6) & ~(state_read_read_fu_118_p2 == 5'd7) & ~(state_read_read_fu_118_p2 == 5'd0) & ~(state_read_read_fu_118_p2 == 5'd1) & ~(state_read_read_fu_118_p2 == 5'd2) & ~(state_read_read_fu_118_p2 == 5'd3) & ~(state_read_read_fu_118_p2 == 5'd4) & (1'b1 == ap_ce) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)) | ((state_read_read_fu_118_p2 == 5'd2) & (1'b1 == ap_ce) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)) | ((state_read_read_fu_118_p2 == 5'd4) & (1'b1 == ap_ce) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        HammingTable_aTransi_30_reg_1000 <= p_read2;
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2) & (grp_fu_1113_p2 == 1'd1) & (state_read_reg_1215 == 5'd3)) | ((1'b1 == ap_ce) & (grp_fu_1113_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2) & (state_read_reg_1215 == 5'd3)) | ((state_read_reg_1215 == 5'd5) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2) & (grp_fu_1113_p2 == 1'd1)) | ((state_read_reg_1215 == 5'd5) & (1'b1 == ap_ce) & (grp_fu_1113_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)) | ((state_read_reg_1215 == 5'd7) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2) & (grp_fu_1113_p2 == 1'd1)) | ((state_read_reg_1215 == 5'd7) & (1'b1 == ap_ce) & (grp_fu_1113_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)))) begin
        HammingTable_bTransi_20_reg_740 <= p_read423_reg_1414;
    end else if ((((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2) & (grp_fu_1113_p2 == 1'd1) & (state_read_reg_1215 == 5'd1)) | ((1'b1 == ap_ce) & (grp_fu_1113_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2) & (state_read_reg_1215 == 5'd1)))) begin
        HammingTable_bTransi_20_reg_740 <= ap_phi_mux_HammingTable_bTransi_phi_fu_496_p4;
    end else if ((((state_read_read_fu_118_p2 == 5'd6) & (1'b1 == ap_ce) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)) | (~(state_read_read_fu_118_p2 == 5'd5) & ~(state_read_read_fu_118_p2 == 5'd6) & ~(state_read_read_fu_118_p2 == 5'd7) & ~(state_read_read_fu_118_p2 == 5'd0) & ~(state_read_read_fu_118_p2 == 5'd1) & ~(state_read_read_fu_118_p2 == 5'd2) & ~(state_read_read_fu_118_p2 == 5'd3) & ~(state_read_read_fu_118_p2 == 5'd4) & (1'b1 == ap_ce) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)) | ((state_read_read_fu_118_p2 == 5'd0) & (1'b1 == ap_ce) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)) | ((state_read_read_fu_118_p2 == 5'd2) & (1'b1 == ap_ce) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)) | ((state_read_read_fu_118_p2 == 5'd4) & (1'b1 == ap_ce) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        HammingTable_bTransi_20_reg_740 <= p_read4;
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2) & (grp_fu_1113_p2 == 1'd1) & (state_read_reg_1215 == 5'd3)) | ((1'b1 == ap_ce) & (grp_fu_1113_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2) & (state_read_reg_1215 == 5'd3)))) begin
        HammingTable_cTransi_30_reg_513 <= ap_phi_mux_HammingTable_cTransi_phi_fu_476_p4;
    end else if ((((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2) & (grp_fu_1113_p2 == 1'd1) & (state_read_reg_1215 == 5'd1)) | ((1'b1 == ap_ce) & (grp_fu_1113_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2) & (state_read_reg_1215 == 5'd1)) | ((state_read_reg_1215 == 5'd5) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2) & (grp_fu_1113_p2 == 1'd1)) | ((state_read_reg_1215 == 5'd5) & (1'b1 == ap_ce) & (grp_fu_1113_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)) | ((state_read_reg_1215 == 5'd7) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2) & (grp_fu_1113_p2 == 1'd1)) | ((state_read_reg_1215 == 5'd7) & (1'b1 == ap_ce) & (grp_fu_1113_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)))) begin
        HammingTable_cTransi_30_reg_513 <= p_read625_reg_1384;
    end else if (((state_read_read_fu_118_p2 == 5'd2) & (1'b1 == ap_ce) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        HammingTable_cTransi_30_reg_513 <= grp_calculateDistanceFor_fu_1033_ap_return;
    end else if ((((state_read_read_fu_118_p2 == 5'd6) & (1'b1 == ap_ce) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)) | (~(state_read_read_fu_118_p2 == 5'd5) & ~(state_read_read_fu_118_p2 == 5'd6) & ~(state_read_read_fu_118_p2 == 5'd7) & ~(state_read_read_fu_118_p2 == 5'd0) & ~(state_read_read_fu_118_p2 == 5'd1) & ~(state_read_read_fu_118_p2 == 5'd2) & ~(state_read_read_fu_118_p2 == 5'd3) & ~(state_read_read_fu_118_p2 == 5'd4) & (1'b1 == ap_ce) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)) | ((state_read_read_fu_118_p2 == 5'd0) & (1'b1 == ap_ce) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)) | ((state_read_read_fu_118_p2 == 5'd4) & (1'b1 == ap_ce) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        HammingTable_cTransi_30_reg_513 <= p_read6;
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2) & (grp_fu_1113_p2 == 1'd1) & (state_read_reg_1215 == 5'd3)) | ((1'b1 == ap_ce) & (grp_fu_1113_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2) & (state_read_reg_1215 == 5'd3)))) begin
        HammingTable_dTransi_20_reg_578 <= ap_phi_mux_HammingTable_dTransi_phi_fu_486_p4;
    end else if ((((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2) & (grp_fu_1113_p2 == 1'd1) & (state_read_reg_1215 == 5'd1)) | ((1'b1 == ap_ce) & (grp_fu_1113_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2) & (state_read_reg_1215 == 5'd1)) | ((state_read_reg_1215 == 5'd5) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2) & (grp_fu_1113_p2 == 1'd1)) | ((state_read_reg_1215 == 5'd5) & (1'b1 == ap_ce) & (grp_fu_1113_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)) | ((state_read_reg_1215 == 5'd7) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2) & (grp_fu_1113_p2 == 1'd1)) | ((state_read_reg_1215 == 5'd7) & (1'b1 == ap_ce) & (grp_fu_1113_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)))) begin
        HammingTable_dTransi_20_reg_578 <= p_read827_reg_1354;
    end else if ((((state_read_read_fu_118_p2 == 5'd6) & (1'b1 == ap_ce) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)) | (~(state_read_read_fu_118_p2 == 5'd5) & ~(state_read_read_fu_118_p2 == 5'd6) & ~(state_read_read_fu_118_p2 == 5'd7) & ~(state_read_read_fu_118_p2 == 5'd0) & ~(state_read_read_fu_118_p2 == 5'd1) & ~(state_read_read_fu_118_p2 == 5'd2) & ~(state_read_read_fu_118_p2 == 5'd3) & ~(state_read_read_fu_118_p2 == 5'd4) & (1'b1 == ap_ce) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)) | ((state_read_read_fu_118_p2 == 5'd0) & (1'b1 == ap_ce) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)) | ((state_read_read_fu_118_p2 == 5'd2) & (1'b1 == ap_ce) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)) | ((state_read_read_fu_118_p2 == 5'd4) & (1'b1 == ap_ce) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        HammingTable_dTransi_20_reg_578 <= p_read8;
    end
end

always @ (posedge ap_clk) begin
    if ((((state_read_reg_1215 == 5'd5) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2) & (grp_fu_1113_p2 == 1'd1)) | ((state_read_reg_1215 == 5'd5) & (1'b1 == ap_ce) & (grp_fu_1113_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)))) begin
        HammingTable_eTransi_30_reg_675 <= ap_phi_mux_HammingTable_eTransi_phi_fu_456_p4;
    end else if ((((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2) & (grp_fu_1113_p2 == 1'd1) & (state_read_reg_1215 == 5'd1)) | ((1'b1 == ap_ce) & (grp_fu_1113_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2) & (state_read_reg_1215 == 5'd1)) | ((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2) & (grp_fu_1113_p2 == 1'd1) & (state_read_reg_1215 == 5'd3)) | ((1'b1 == ap_ce) & (grp_fu_1113_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2) & (state_read_reg_1215 == 5'd3)) | ((state_read_reg_1215 == 5'd7) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2) & (grp_fu_1113_p2 == 1'd1)) | ((state_read_reg_1215 == 5'd7) & (1'b1 == ap_ce) & (grp_fu_1113_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)))) begin
        HammingTable_eTransi_30_reg_675 <= p_read1029_reg_1324;
    end else if (((state_read_read_fu_118_p2 == 5'd4) & (1'b1 == ap_ce) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        HammingTable_eTransi_30_reg_675 <= grp_calculateDistanceFor_fu_1033_ap_return;
    end else if ((((state_read_read_fu_118_p2 == 5'd6) & (1'b1 == ap_ce) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)) | (~(state_read_read_fu_118_p2 == 5'd5) & ~(state_read_read_fu_118_p2 == 5'd6) & ~(state_read_read_fu_118_p2 == 5'd7) & ~(state_read_read_fu_118_p2 == 5'd0) & ~(state_read_read_fu_118_p2 == 5'd1) & ~(state_read_read_fu_118_p2 == 5'd2) & ~(state_read_read_fu_118_p2 == 5'd3) & ~(state_read_read_fu_118_p2 == 5'd4) & (1'b1 == ap_ce) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)) | ((state_read_read_fu_118_p2 == 5'd0) & (1'b1 == ap_ce) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)) | ((state_read_read_fu_118_p2 == 5'd2) & (1'b1 == ap_ce) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        HammingTable_eTransi_30_reg_675 <= p_read10;
    end
end

always @ (posedge ap_clk) begin
    if ((((state_read_reg_1215 == 5'd5) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2) & (grp_fu_1113_p2 == 1'd1)) | ((state_read_reg_1215 == 5'd5) & (1'b1 == ap_ce) & (grp_fu_1113_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)))) begin
        HammingTable_fTransi_20_reg_773 <= ap_phi_mux_HammingTable_fTransi_phi_fu_466_p4;
    end else if ((((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2) & (grp_fu_1113_p2 == 1'd1) & (state_read_reg_1215 == 5'd1)) | ((1'b1 == ap_ce) & (grp_fu_1113_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2) & (state_read_reg_1215 == 5'd1)) | ((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2) & (grp_fu_1113_p2 == 1'd1) & (state_read_reg_1215 == 5'd3)) | ((1'b1 == ap_ce) & (grp_fu_1113_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2) & (state_read_reg_1215 == 5'd3)) | ((state_read_reg_1215 == 5'd7) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2) & (grp_fu_1113_p2 == 1'd1)) | ((state_read_reg_1215 == 5'd7) & (1'b1 == ap_ce) & (grp_fu_1113_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)))) begin
        HammingTable_fTransi_20_reg_773 <= p_read_31_reg_1294;
    end else if ((((state_read_read_fu_118_p2 == 5'd6) & (1'b1 == ap_ce) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)) | (~(state_read_read_fu_118_p2 == 5'd5) & ~(state_read_read_fu_118_p2 == 5'd6) & ~(state_read_read_fu_118_p2 == 5'd7) & ~(state_read_read_fu_118_p2 == 5'd0) & ~(state_read_read_fu_118_p2 == 5'd1) & ~(state_read_read_fu_118_p2 == 5'd2) & ~(state_read_read_fu_118_p2 == 5'd3) & ~(state_read_read_fu_118_p2 == 5'd4) & (1'b1 == ap_ce) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)) | ((state_read_read_fu_118_p2 == 5'd0) & (1'b1 == ap_ce) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)) | ((state_read_read_fu_118_p2 == 5'd2) & (1'b1 == ap_ce) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)) | ((state_read_read_fu_118_p2 == 5'd4) & (1'b1 == ap_ce) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        HammingTable_fTransi_20_reg_773 <= p_read12;
    end
end

always @ (posedge ap_clk) begin
    if ((((state_read_reg_1215 == 5'd7) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2) & (grp_fu_1113_p2 == 1'd1)) | ((state_read_reg_1215 == 5'd7) & (1'b1 == ap_ce) & (grp_fu_1113_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)))) begin
        HammingTable_gTransi_30_reg_838 <= ap_phi_mux_HammingTable_gTransi_phi_fu_436_p4;
    end else if ((((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2) & (grp_fu_1113_p2 == 1'd1) & (state_read_reg_1215 == 5'd1)) | ((1'b1 == ap_ce) & (grp_fu_1113_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2) & (state_read_reg_1215 == 5'd1)) | ((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2) & (grp_fu_1113_p2 == 1'd1) & (state_read_reg_1215 == 5'd3)) | ((1'b1 == ap_ce) & (grp_fu_1113_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2) & (state_read_reg_1215 == 5'd3)) | ((state_read_reg_1215 == 5'd5) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2) & (grp_fu_1113_p2 == 1'd1)) | ((state_read_reg_1215 == 5'd5) & (1'b1 == ap_ce) & (grp_fu_1113_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)))) begin
        HammingTable_gTransi_30_reg_838 <= p_read_29_reg_1264;
    end else if (((state_read_read_fu_118_p2 == 5'd6) & (1'b1 == ap_ce) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        HammingTable_gTransi_30_reg_838 <= grp_calculateDistanceFor_fu_1033_ap_return;
    end else if (((~(state_read_read_fu_118_p2 == 5'd5) & ~(state_read_read_fu_118_p2 == 5'd6) & ~(state_read_read_fu_118_p2 == 5'd7) & ~(state_read_read_fu_118_p2 == 5'd0) & ~(state_read_read_fu_118_p2 == 5'd1) & ~(state_read_read_fu_118_p2 == 5'd2) & ~(state_read_read_fu_118_p2 == 5'd3) & ~(state_read_read_fu_118_p2 == 5'd4) & (1'b1 == ap_ce) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)) | ((state_read_read_fu_118_p2 == 5'd0) & (1'b1 == ap_ce) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)) | ((state_read_read_fu_118_p2 == 5'd2) & (1'b1 == ap_ce) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)) | ((state_read_read_fu_118_p2 == 5'd4) & (1'b1 == ap_ce) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        HammingTable_gTransi_30_reg_838 <= p_read14;
    end
end

always @ (posedge ap_clk) begin
    if ((((state_read_reg_1215 == 5'd7) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2) & (grp_fu_1113_p2 == 1'd1)) | ((state_read_reg_1215 == 5'd7) & (1'b1 == ap_ce) & (grp_fu_1113_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)))) begin
        HammingTable_hTransi_20_reg_935 <= ap_phi_mux_HammingTable_hTransi_phi_fu_446_p4;
    end else if ((((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2) & (grp_fu_1113_p2 == 1'd1) & (state_read_reg_1215 == 5'd1)) | ((1'b1 == ap_ce) & (grp_fu_1113_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2) & (state_read_reg_1215 == 5'd1)) | ((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2) & (grp_fu_1113_p2 == 1'd1) & (state_read_reg_1215 == 5'd3)) | ((1'b1 == ap_ce) & (grp_fu_1113_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2) & (state_read_reg_1215 == 5'd3)) | ((state_read_reg_1215 == 5'd5) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2) & (grp_fu_1113_p2 == 1'd1)) | ((state_read_reg_1215 == 5'd5) & (1'b1 == ap_ce) & (grp_fu_1113_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)))) begin
        HammingTable_hTransi_20_reg_935 <= p_read_27_reg_1234;
    end else if ((((state_read_read_fu_118_p2 == 5'd6) & (1'b1 == ap_ce) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)) | (~(state_read_read_fu_118_p2 == 5'd5) & ~(state_read_read_fu_118_p2 == 5'd6) & ~(state_read_read_fu_118_p2 == 5'd7) & ~(state_read_read_fu_118_p2 == 5'd0) & ~(state_read_read_fu_118_p2 == 5'd1) & ~(state_read_read_fu_118_p2 == 5'd2) & ~(state_read_read_fu_118_p2 == 5'd3) & ~(state_read_read_fu_118_p2 == 5'd4) & (1'b1 == ap_ce) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)) | ((state_read_read_fu_118_p2 == 5'd0) & (1'b1 == ap_ce) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)) | ((state_read_read_fu_118_p2 == 5'd2) & (1'b1 == ap_ce) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)) | ((state_read_read_fu_118_p2 == 5'd4) & (1'b1 == ap_ce) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        HammingTable_hTransi_20_reg_935 <= p_read16;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2) & (grp_fu_1113_p2 == 1'd1) & (state_read_reg_1215 == 5'd3))) begin
        phi_ln228_1_reg_611 <= reg_1094;
    end else if (((1'b1 == ap_ce) & (grp_fu_1113_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2) & (state_read_reg_1215 == 5'd3))) begin
        phi_ln228_1_reg_611 <= 8'd255;
    end else if ((((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2) & (grp_fu_1113_p2 == 1'd1) & (state_read_reg_1215 == 5'd1)) | ((1'b1 == ap_ce) & (grp_fu_1113_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2) & (state_read_reg_1215 == 5'd1)) | ((state_read_reg_1215 == 5'd5) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2) & (grp_fu_1113_p2 == 1'd1)) | ((state_read_reg_1215 == 5'd5) & (1'b1 == ap_ce) & (grp_fu_1113_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)) | ((state_read_reg_1215 == 5'd7) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2) & (grp_fu_1113_p2 == 1'd1)) | ((state_read_reg_1215 == 5'd7) & (1'b1 == ap_ce) & (grp_fu_1113_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)))) begin
        phi_ln228_1_reg_611 <= p_read928_reg_1339;
    end else if ((((state_read_read_fu_118_p2 == 5'd6) & (1'b1 == ap_ce) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)) | (~(state_read_read_fu_118_p2 == 5'd5) & ~(state_read_read_fu_118_p2 == 5'd6) & ~(state_read_read_fu_118_p2 == 5'd7) & ~(state_read_read_fu_118_p2 == 5'd0) & ~(state_read_read_fu_118_p2 == 5'd1) & ~(state_read_read_fu_118_p2 == 5'd2) & ~(state_read_read_fu_118_p2 == 5'd3) & ~(state_read_read_fu_118_p2 == 5'd4) & (1'b1 == ap_ce) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)) | ((state_read_read_fu_118_p2 == 5'd0) & (1'b1 == ap_ce) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)) | ((state_read_read_fu_118_p2 == 5'd2) & (1'b1 == ap_ce) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)) | ((state_read_read_fu_118_p2 == 5'd4) & (1'b1 == ap_ce) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        phi_ln228_1_reg_611 <= p_read9;
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2) & (grp_fu_1113_p2 == 1'd1) & (state_read_reg_1215 == 5'd3)) | ((1'b1 == ap_ce) & (grp_fu_1113_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2) & (state_read_reg_1215 == 5'd3)) | ((state_read_reg_1215 == 5'd5) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2) & (grp_fu_1113_p2 == 1'd1)) | ((state_read_reg_1215 == 5'd5) & (1'b1 == ap_ce) & (grp_fu_1113_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)) | ((state_read_reg_1215 == 5'd7) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2) & (grp_fu_1113_p2 == 1'd1)) | ((state_read_reg_1215 == 5'd7) & (1'b1 == ap_ce) & (grp_fu_1113_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)))) begin
        phi_ln228_2_reg_643 <= p_read524_reg_1399;
    end else if (((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2) & (grp_fu_1113_p2 == 1'd1) & (state_read_reg_1215 == 5'd1))) begin
        phi_ln228_2_reg_643 <= reg_1094;
    end else if (((1'b1 == ap_ce) & (grp_fu_1113_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2) & (state_read_reg_1215 == 5'd1))) begin
        phi_ln228_2_reg_643 <= 8'd255;
    end else if ((((state_read_read_fu_118_p2 == 5'd6) & (1'b1 == ap_ce) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)) | (~(state_read_read_fu_118_p2 == 5'd5) & ~(state_read_read_fu_118_p2 == 5'd6) & ~(state_read_read_fu_118_p2 == 5'd7) & ~(state_read_read_fu_118_p2 == 5'd0) & ~(state_read_read_fu_118_p2 == 5'd1) & ~(state_read_read_fu_118_p2 == 5'd2) & ~(state_read_read_fu_118_p2 == 5'd3) & ~(state_read_read_fu_118_p2 == 5'd4) & (1'b1 == ap_ce) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)) | ((state_read_read_fu_118_p2 == 5'd0) & (1'b1 == ap_ce) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)) | ((state_read_read_fu_118_p2 == 5'd2) & (1'b1 == ap_ce) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)) | ((state_read_read_fu_118_p2 == 5'd4) & (1'b1 == ap_ce) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        phi_ln228_2_reg_643 <= p_read5;
    end
end

always @ (posedge ap_clk) begin
    if (((state_read_reg_1215 == 5'd5) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2) & (grp_fu_1113_p2 == 1'd1))) begin
        phi_ln228_3_reg_708 <= 8'd255;
    end else if ((((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2) & (grp_fu_1113_p2 == 1'd1) & (state_read_reg_1215 == 5'd1)) | ((1'b1 == ap_ce) & (grp_fu_1113_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2) & (state_read_reg_1215 == 5'd1)) | ((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2) & (grp_fu_1113_p2 == 1'd1) & (state_read_reg_1215 == 5'd3)) | ((1'b1 == ap_ce) & (grp_fu_1113_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2) & (state_read_reg_1215 == 5'd3)) | ((state_read_reg_1215 == 5'd5) & (1'b1 == ap_ce) & (grp_fu_1113_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)) | ((state_read_reg_1215 == 5'd7) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2) & (grp_fu_1113_p2 == 1'd1)) | ((state_read_reg_1215 == 5'd7) & (1'b1 == ap_ce) & (grp_fu_1113_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)))) begin
        phi_ln228_3_reg_708 <= p_read_32_reg_1309;
    end else if (((state_read_read_fu_118_p2 == 5'd4) & (1'b1 == ap_ce) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        phi_ln228_3_reg_708 <= grp_calculateDistanceFor_fu_1047_ap_return;
    end else if ((((state_read_read_fu_118_p2 == 5'd6) & (1'b1 == ap_ce) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)) | (~(state_read_read_fu_118_p2 == 5'd5) & ~(state_read_read_fu_118_p2 == 5'd6) & ~(state_read_read_fu_118_p2 == 5'd7) & ~(state_read_read_fu_118_p2 == 5'd0) & ~(state_read_read_fu_118_p2 == 5'd1) & ~(state_read_read_fu_118_p2 == 5'd2) & ~(state_read_read_fu_118_p2 == 5'd3) & ~(state_read_read_fu_118_p2 == 5'd4) & (1'b1 == ap_ce) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)) | ((state_read_read_fu_118_p2 == 5'd0) & (1'b1 == ap_ce) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)) | ((state_read_read_fu_118_p2 == 5'd2) & (1'b1 == ap_ce) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        phi_ln228_3_reg_708 <= p_read11;
    end
end

always @ (posedge ap_clk) begin
    if (((state_read_reg_1215 == 5'd5) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2) & (grp_fu_1113_p2 == 1'd1))) begin
        phi_ln228_4_reg_806 <= reg_1094;
    end else if (((state_read_reg_1215 == 5'd5) & (1'b1 == ap_ce) & (grp_fu_1113_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        phi_ln228_4_reg_806 <= 8'd255;
    end else if ((((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2) & (grp_fu_1113_p2 == 1'd1) & (state_read_reg_1215 == 5'd1)) | ((1'b1 == ap_ce) & (grp_fu_1113_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2) & (state_read_reg_1215 == 5'd1)) | ((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2) & (grp_fu_1113_p2 == 1'd1) & (state_read_reg_1215 == 5'd3)) | ((1'b1 == ap_ce) & (grp_fu_1113_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2) & (state_read_reg_1215 == 5'd3)) | ((state_read_reg_1215 == 5'd7) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2) & (grp_fu_1113_p2 == 1'd1)) | ((state_read_reg_1215 == 5'd7) & (1'b1 == ap_ce) & (grp_fu_1113_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)))) begin
        phi_ln228_4_reg_806 <= p_read_30_reg_1279;
    end else if ((((state_read_read_fu_118_p2 == 5'd6) & (1'b1 == ap_ce) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)) | (~(state_read_read_fu_118_p2 == 5'd5) & ~(state_read_read_fu_118_p2 == 5'd6) & ~(state_read_read_fu_118_p2 == 5'd7) & ~(state_read_read_fu_118_p2 == 5'd0) & ~(state_read_read_fu_118_p2 == 5'd1) & ~(state_read_read_fu_118_p2 == 5'd2) & ~(state_read_read_fu_118_p2 == 5'd3) & ~(state_read_read_fu_118_p2 == 5'd4) & (1'b1 == ap_ce) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)) | ((state_read_read_fu_118_p2 == 5'd0) & (1'b1 == ap_ce) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)) | ((state_read_read_fu_118_p2 == 5'd2) & (1'b1 == ap_ce) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)) | ((state_read_read_fu_118_p2 == 5'd4) & (1'b1 == ap_ce) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        phi_ln228_4_reg_806 <= p_read13;
    end
end

always @ (posedge ap_clk) begin
    if (((state_read_reg_1215 == 5'd7) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2) & (grp_fu_1113_p2 == 1'd1))) begin
        phi_ln228_5_reg_871 <= 8'd255;
    end else if ((((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2) & (grp_fu_1113_p2 == 1'd1) & (state_read_reg_1215 == 5'd1)) | ((1'b1 == ap_ce) & (grp_fu_1113_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2) & (state_read_reg_1215 == 5'd1)) | ((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2) & (grp_fu_1113_p2 == 1'd1) & (state_read_reg_1215 == 5'd3)) | ((1'b1 == ap_ce) & (grp_fu_1113_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2) & (state_read_reg_1215 == 5'd3)) | ((state_read_reg_1215 == 5'd5) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2) & (grp_fu_1113_p2 == 1'd1)) | ((state_read_reg_1215 == 5'd5) & (1'b1 == ap_ce) & (grp_fu_1113_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)) | ((state_read_reg_1215 == 5'd7) & (1'b1 == ap_ce) & (grp_fu_1113_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)))) begin
        phi_ln228_5_reg_871 <= p_read_28_reg_1249;
    end else if (((state_read_read_fu_118_p2 == 5'd6) & (1'b1 == ap_ce) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        phi_ln228_5_reg_871 <= grp_calculateDistanceFor_fu_1047_ap_return;
    end else if (((~(state_read_read_fu_118_p2 == 5'd5) & ~(state_read_read_fu_118_p2 == 5'd6) & ~(state_read_read_fu_118_p2 == 5'd7) & ~(state_read_read_fu_118_p2 == 5'd0) & ~(state_read_read_fu_118_p2 == 5'd1) & ~(state_read_read_fu_118_p2 == 5'd2) & ~(state_read_read_fu_118_p2 == 5'd3) & ~(state_read_read_fu_118_p2 == 5'd4) & (1'b1 == ap_ce) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)) | ((state_read_read_fu_118_p2 == 5'd0) & (1'b1 == ap_ce) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)) | ((state_read_read_fu_118_p2 == 5'd2) & (1'b1 == ap_ce) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)) | ((state_read_read_fu_118_p2 == 5'd4) & (1'b1 == ap_ce) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        phi_ln228_5_reg_871 <= p_read15;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2) & (grp_fu_1113_p2 == 1'd1) & (state_read_reg_1215 == 5'd1))) begin
        phi_ln228_6_reg_903 <= 8'd255;
    end else if ((((1'b1 == ap_ce) & (grp_fu_1113_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2) & (state_read_reg_1215 == 5'd1)) | ((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2) & (grp_fu_1113_p2 == 1'd1) & (state_read_reg_1215 == 5'd3)) | ((1'b1 == ap_ce) & (grp_fu_1113_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2) & (state_read_reg_1215 == 5'd3)) | ((state_read_reg_1215 == 5'd5) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2) & (grp_fu_1113_p2 == 1'd1)) | ((state_read_reg_1215 == 5'd5) & (1'b1 == ap_ce) & (grp_fu_1113_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)) | ((state_read_reg_1215 == 5'd7) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2) & (grp_fu_1113_p2 == 1'd1)) | ((state_read_reg_1215 == 5'd7) & (1'b1 == ap_ce) & (grp_fu_1113_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)))) begin
        phi_ln228_6_reg_903 <= p_read322_reg_1429;
    end else if (((state_read_read_fu_118_p2 == 5'd0) & (1'b1 == ap_ce) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        phi_ln228_6_reg_903 <= grp_calculateDistanceFor_fu_1047_ap_return;
    end else if ((((state_read_read_fu_118_p2 == 5'd6) & (1'b1 == ap_ce) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)) | (~(state_read_read_fu_118_p2 == 5'd5) & ~(state_read_read_fu_118_p2 == 5'd6) & ~(state_read_read_fu_118_p2 == 5'd7) & ~(state_read_read_fu_118_p2 == 5'd0) & ~(state_read_read_fu_118_p2 == 5'd1) & ~(state_read_read_fu_118_p2 == 5'd2) & ~(state_read_read_fu_118_p2 == 5'd3) & ~(state_read_read_fu_118_p2 == 5'd4) & (1'b1 == ap_ce) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)) | ((state_read_read_fu_118_p2 == 5'd2) & (1'b1 == ap_ce) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)) | ((state_read_read_fu_118_p2 == 5'd4) & (1'b1 == ap_ce) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        phi_ln228_6_reg_903 <= p_read3;
    end
end

always @ (posedge ap_clk) begin
    if (((state_read_reg_1215 == 5'd7) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2) & (grp_fu_1113_p2 == 1'd1))) begin
        phi_ln228_7_reg_968 <= reg_1094;
    end else if (((state_read_reg_1215 == 5'd7) & (1'b1 == ap_ce) & (grp_fu_1113_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        phi_ln228_7_reg_968 <= 8'd255;
    end else if ((((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2) & (grp_fu_1113_p2 == 1'd1) & (state_read_reg_1215 == 5'd1)) | ((1'b1 == ap_ce) & (grp_fu_1113_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2) & (state_read_reg_1215 == 5'd1)) | ((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2) & (grp_fu_1113_p2 == 1'd1) & (state_read_reg_1215 == 5'd3)) | ((1'b1 == ap_ce) & (grp_fu_1113_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2) & (state_read_reg_1215 == 5'd3)) | ((state_read_reg_1215 == 5'd5) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2) & (grp_fu_1113_p2 == 1'd1)) | ((state_read_reg_1215 == 5'd5) & (1'b1 == ap_ce) & (grp_fu_1113_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)))) begin
        phi_ln228_7_reg_968 <= p_read_26_reg_1219;
    end else if ((((state_read_read_fu_118_p2 == 5'd6) & (1'b1 == ap_ce) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)) | (~(state_read_read_fu_118_p2 == 5'd5) & ~(state_read_read_fu_118_p2 == 5'd6) & ~(state_read_read_fu_118_p2 == 5'd7) & ~(state_read_read_fu_118_p2 == 5'd0) & ~(state_read_read_fu_118_p2 == 5'd1) & ~(state_read_read_fu_118_p2 == 5'd2) & ~(state_read_read_fu_118_p2 == 5'd3) & ~(state_read_read_fu_118_p2 == 5'd4) & (1'b1 == ap_ce) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)) | ((state_read_read_fu_118_p2 == 5'd0) & (1'b1 == ap_ce) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)) | ((state_read_read_fu_118_p2 == 5'd2) & (1'b1 == ap_ce) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)) | ((state_read_read_fu_118_p2 == 5'd4) & (1'b1 == ap_ce) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        phi_ln228_7_reg_968 <= p_read17;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2) & (grp_fu_1113_p2 == 1'd1) & (state_read_reg_1215 == 5'd3))) begin
        phi_ln228_reg_546 <= 8'd255;
    end else if ((((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2) & (grp_fu_1113_p2 == 1'd1) & (state_read_reg_1215 == 5'd1)) | ((1'b1 == ap_ce) & (grp_fu_1113_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2) & (state_read_reg_1215 == 5'd1)) | ((1'b1 == ap_ce) & (grp_fu_1113_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2) & (state_read_reg_1215 == 5'd3)) | ((state_read_reg_1215 == 5'd5) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2) & (grp_fu_1113_p2 == 1'd1)) | ((state_read_reg_1215 == 5'd5) & (1'b1 == ap_ce) & (grp_fu_1113_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)) | ((state_read_reg_1215 == 5'd7) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2) & (grp_fu_1113_p2 == 1'd1)) | ((state_read_reg_1215 == 5'd7) & (1'b1 == ap_ce) & (grp_fu_1113_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)))) begin
        phi_ln228_reg_546 <= p_read726_reg_1369;
    end else if (((state_read_read_fu_118_p2 == 5'd2) & (1'b1 == ap_ce) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        phi_ln228_reg_546 <= grp_calculateDistanceFor_fu_1047_ap_return;
    end else if ((((state_read_read_fu_118_p2 == 5'd6) & (1'b1 == ap_ce) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)) | (~(state_read_read_fu_118_p2 == 5'd5) & ~(state_read_read_fu_118_p2 == 5'd6) & ~(state_read_read_fu_118_p2 == 5'd7) & ~(state_read_read_fu_118_p2 == 5'd0) & ~(state_read_read_fu_118_p2 == 5'd1) & ~(state_read_read_fu_118_p2 == 5'd2) & ~(state_read_read_fu_118_p2 == 5'd3) & ~(state_read_read_fu_118_p2 == 5'd4) & (1'b1 == ap_ce) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)) | ((state_read_read_fu_118_p2 == 5'd0) & (1'b1 == ap_ce) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)) | ((state_read_read_fu_118_p2 == 5'd4) & (1'b1 == ap_ce) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        phi_ln228_reg_546 <= p_read7;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_ce) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        p_read1029_reg_1324 <= p_read10;
        p_read221_reg_1444 <= p_read2;
        p_read322_reg_1429 <= p_read3;
        p_read423_reg_1414 <= p_read4;
        p_read524_reg_1399 <= p_read5;
        p_read625_reg_1384 <= p_read6;
        p_read726_reg_1369 <= p_read7;
        p_read827_reg_1354 <= p_read8;
        p_read928_reg_1339 <= p_read9;
        p_read_26_reg_1219 <= p_read17;
        p_read_27_reg_1234 <= p_read16;
        p_read_28_reg_1249 <= p_read15;
        p_read_29_reg_1264 <= p_read14;
        p_read_30_reg_1279 <= p_read13;
        p_read_31_reg_1294 <= p_read12;
        p_read_32_reg_1309 <= p_read11;
        state_read_reg_1215 <= state;
    end
end

always @ (posedge ap_clk) begin
    if ((((state_read_read_fu_118_p2 == 5'd5) & (1'b1 == ap_ce) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)) | ((state_read_read_fu_118_p2 == 5'd6) & (1'b1 == ap_ce) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)) | ((state_read_read_fu_118_p2 == 5'd7) & (1'b1 == ap_ce) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)) | ((state_read_read_fu_118_p2 == 5'd0) & (1'b1 == ap_ce) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)) | ((state_read_read_fu_118_p2 == 5'd1) & (1'b1 == ap_ce) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)) | ((state_read_read_fu_118_p2 == 5'd2) & (1'b1 == ap_ce) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)) | ((state_read_read_fu_118_p2 == 5'd3) & (1'b1 == ap_ce) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)) | ((state_read_read_fu_118_p2 == 5'd4) & (1'b1 == ap_ce) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        reg_1081 <= grp_calculateDistanceFor_fu_1033_ap_return;
        reg_1094 <= grp_calculateDistanceFor_fu_1047_ap_return;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (grp_fu_1107_p2 == 1'd1) & (state_read_reg_1215 == 5'd1))) begin
        HammingTable_hammingDistances_finalStates_address0 = HammingTable_hamming_43_reg_1489;
    end else if (((1'b1 == ap_CS_fsm_state2) & (grp_fu_1107_p2 == 1'd1) & (state_read_reg_1215 == 5'd3))) begin
        HammingTable_hammingDistances_finalStates_address0 = HammingTable_hamming_49_reg_1479;
    end else if (((state_read_reg_1215 == 5'd5) & (1'b1 == ap_CS_fsm_state2) & (grp_fu_1107_p2 == 1'd1))) begin
        HammingTable_hammingDistances_finalStates_address0 = HammingTable_hamming_55_reg_1469;
    end else if (((state_read_reg_1215 == 5'd7) & (1'b1 == ap_CS_fsm_state2) & (grp_fu_1107_p2 == 1'd1))) begin
        HammingTable_hammingDistances_finalStates_address0 = HammingTable_hamming_61_reg_1459;
    end else if (((state_read_read_fu_118_p2 == 5'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        HammingTable_hammingDistances_finalStates_address0 = HammingTable_hamming_gep_fu_415_p3;
    end else if (((state_read_read_fu_118_p2 == 5'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        HammingTable_hammingDistances_finalStates_address0 = 64'd0;
    end else if (((state_read_read_fu_118_p2 == 5'd2) & (1'b1 == ap_CS_fsm_state1))) begin
        HammingTable_hammingDistances_finalStates_address0 = HammingTable_hamming_47_gep_fu_379_p3;
    end else if (((state_read_read_fu_118_p2 == 5'd3) & (1'b1 == ap_CS_fsm_state1))) begin
        HammingTable_hammingDistances_finalStates_address0 = 64'd1;
    end else if (((state_read_read_fu_118_p2 == 5'd4) & (1'b1 == ap_CS_fsm_state1))) begin
        HammingTable_hammingDistances_finalStates_address0 = HammingTable_hamming_53_gep_fu_343_p3;
    end else if (((state_read_read_fu_118_p2 == 5'd5) & (1'b1 == ap_CS_fsm_state1))) begin
        HammingTable_hammingDistances_finalStates_address0 = 64'd2;
    end else if (((state_read_read_fu_118_p2 == 5'd6) & (1'b1 == ap_CS_fsm_state1))) begin
        HammingTable_hammingDistances_finalStates_address0 = HammingTable_hamming_59_gep_fu_307_p3;
    end else if (((state_read_read_fu_118_p2 == 5'd7) & (1'b1 == ap_CS_fsm_state1))) begin
        HammingTable_hammingDistances_finalStates_address0 = 64'd3;
    end else begin
        HammingTable_hammingDistances_finalStates_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (grp_fu_1113_p2 == 1'd1) & (state_read_reg_1215 == 5'd1))) begin
        HammingTable_hammingDistances_finalStates_address1 = HammingTable_hamming_45_reg_1494;
    end else if (((1'b1 == ap_CS_fsm_state2) & (grp_fu_1113_p2 == 1'd1) & (state_read_reg_1215 == 5'd3))) begin
        HammingTable_hammingDistances_finalStates_address1 = HammingTable_hamming_51_reg_1484;
    end else if (((state_read_reg_1215 == 5'd5) & (1'b1 == ap_CS_fsm_state2) & (grp_fu_1113_p2 == 1'd1))) begin
        HammingTable_hammingDistances_finalStates_address1 = HammingTable_hamming_57_reg_1474;
    end else if (((state_read_reg_1215 == 5'd7) & (1'b1 == ap_CS_fsm_state2) & (grp_fu_1113_p2 == 1'd1))) begin
        HammingTable_hammingDistances_finalStates_address1 = HammingTable_hamming_63_reg_1464;
    end else if (((state_read_read_fu_118_p2 == 5'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        HammingTable_hammingDistances_finalStates_address1 = HammingTable_hamming_42_gep_fu_424_p3;
    end else if (((state_read_read_fu_118_p2 == 5'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        HammingTable_hammingDistances_finalStates_address1 = 64'd4;
    end else if (((state_read_read_fu_118_p2 == 5'd2) & (1'b1 == ap_CS_fsm_state1))) begin
        HammingTable_hammingDistances_finalStates_address1 = HammingTable_hamming_48_gep_fu_388_p3;
    end else if (((state_read_read_fu_118_p2 == 5'd3) & (1'b1 == ap_CS_fsm_state1))) begin
        HammingTable_hammingDistances_finalStates_address1 = 64'd5;
    end else if (((state_read_read_fu_118_p2 == 5'd4) & (1'b1 == ap_CS_fsm_state1))) begin
        HammingTable_hammingDistances_finalStates_address1 = HammingTable_hamming_54_gep_fu_352_p3;
    end else if (((state_read_read_fu_118_p2 == 5'd5) & (1'b1 == ap_CS_fsm_state1))) begin
        HammingTable_hammingDistances_finalStates_address1 = 64'd6;
    end else if (((state_read_read_fu_118_p2 == 5'd6) & (1'b1 == ap_CS_fsm_state1))) begin
        HammingTable_hammingDistances_finalStates_address1 = HammingTable_hamming_60_gep_fu_316_p3;
    end else if (((state_read_read_fu_118_p2 == 5'd7) & (1'b1 == ap_CS_fsm_state1))) begin
        HammingTable_hammingDistances_finalStates_address1 = 64'd7;
    end else begin
        HammingTable_hammingDistances_finalStates_address1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2) & (grp_fu_1107_p2 == 1'd1) & (state_read_reg_1215 == 5'd1)) | ((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2) & (grp_fu_1107_p2 == 1'd1) & (state_read_reg_1215 == 5'd3)) | ((state_read_reg_1215 == 5'd5) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2) & (grp_fu_1107_p2 == 1'd1)) | ((state_read_reg_1215 == 5'd7) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2) & (grp_fu_1107_p2 == 1'd1)) | ((state_read_read_fu_118_p2 == 5'd5) & (1'b1 == ap_ce) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)) | ((state_read_read_fu_118_p2 == 5'd6) & (1'b1 == ap_ce) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)) | ((state_read_read_fu_118_p2 == 5'd7) & (1'b1 == ap_ce) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)) | ((state_read_read_fu_118_p2 == 5'd0) & (1'b1 == ap_ce) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)) | ((state_read_read_fu_118_p2 == 5'd1) & (1'b1 == ap_ce) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)) | ((state_read_read_fu_118_p2 == 5'd2) & (1'b1 == ap_ce) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)) | ((state_read_read_fu_118_p2 == 5'd3) & (1'b1 == ap_ce) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)) | ((state_read_read_fu_118_p2 == 5'd4) & (1'b1 == ap_ce) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        HammingTable_hammingDistances_finalStates_ce0 = 1'b1;
    end else begin
        HammingTable_hammingDistances_finalStates_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2) & (grp_fu_1113_p2 == 1'd1) & (state_read_reg_1215 == 5'd1)) | ((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2) & (grp_fu_1113_p2 == 1'd1) & (state_read_reg_1215 == 5'd3)) | ((state_read_reg_1215 == 5'd5) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2) & (grp_fu_1113_p2 == 1'd1)) | ((state_read_reg_1215 == 5'd7) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2) & (grp_fu_1113_p2 == 1'd1)) | ((state_read_read_fu_118_p2 == 5'd5) & (1'b1 == ap_ce) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)) | ((state_read_read_fu_118_p2 == 5'd6) & (1'b1 == ap_ce) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)) | ((state_read_read_fu_118_p2 == 5'd7) & (1'b1 == ap_ce) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)) | ((state_read_read_fu_118_p2 == 5'd0) & (1'b1 == ap_ce) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)) | ((state_read_read_fu_118_p2 == 5'd1) & (1'b1 == ap_ce) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)) | ((state_read_read_fu_118_p2 == 5'd2) & (1'b1 == ap_ce) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)) | ((state_read_read_fu_118_p2 == 5'd3) & (1'b1 == ap_ce) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)) | ((state_read_read_fu_118_p2 == 5'd4) & (1'b1 == ap_ce) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        HammingTable_hammingDistances_finalStates_ce1 = 1'b1;
    end else begin
        HammingTable_hammingDistances_finalStates_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state2) & (grp_fu_1107_p2 == 1'd1) & (state_read_reg_1215 == 5'd1)) | ((1'b1 == ap_CS_fsm_state2) & (grp_fu_1107_p2 == 1'd1) & (state_read_reg_1215 == 5'd3)) | ((state_read_reg_1215 == 5'd5) & (1'b1 == ap_CS_fsm_state2) & (grp_fu_1107_p2 == 1'd1)) | ((state_read_reg_1215 == 5'd7) & (1'b1 == ap_CS_fsm_state2) & (grp_fu_1107_p2 == 1'd1)))) begin
        HammingTable_hammingDistances_finalStates_d0 = reg_1081;
    end else if ((((state_read_read_fu_118_p2 == 5'd6) & (1'b1 == ap_CS_fsm_state1)) | ((state_read_read_fu_118_p2 == 5'd0) & (1'b1 == ap_CS_fsm_state1)) | ((state_read_read_fu_118_p2 == 5'd2) & (1'b1 == ap_CS_fsm_state1)) | ((state_read_read_fu_118_p2 == 5'd4) & (1'b1 == ap_CS_fsm_state1)))) begin
        HammingTable_hammingDistances_finalStates_d0 = grp_calculateDistanceFor_fu_1033_ap_return;
    end else begin
        HammingTable_hammingDistances_finalStates_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state2) & (grp_fu_1113_p2 == 1'd1) & (state_read_reg_1215 == 5'd1)) | ((1'b1 == ap_CS_fsm_state2) & (grp_fu_1113_p2 == 1'd1) & (state_read_reg_1215 == 5'd3)) | ((state_read_reg_1215 == 5'd5) & (1'b1 == ap_CS_fsm_state2) & (grp_fu_1113_p2 == 1'd1)) | ((state_read_reg_1215 == 5'd7) & (1'b1 == ap_CS_fsm_state2) & (grp_fu_1113_p2 == 1'd1)))) begin
        HammingTable_hammingDistances_finalStates_d1 = reg_1094;
    end else if ((((state_read_read_fu_118_p2 == 5'd6) & (1'b1 == ap_CS_fsm_state1)) | ((state_read_read_fu_118_p2 == 5'd0) & (1'b1 == ap_CS_fsm_state1)) | ((state_read_read_fu_118_p2 == 5'd2) & (1'b1 == ap_CS_fsm_state1)) | ((state_read_read_fu_118_p2 == 5'd4) & (1'b1 == ap_CS_fsm_state1)))) begin
        HammingTable_hammingDistances_finalStates_d1 = grp_calculateDistanceFor_fu_1047_ap_return;
    end else begin
        HammingTable_hammingDistances_finalStates_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2) & (grp_fu_1107_p2 == 1'd1) & (state_read_reg_1215 == 5'd1)) | ((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2) & (grp_fu_1107_p2 == 1'd1) & (state_read_reg_1215 == 5'd3)) | ((state_read_reg_1215 == 5'd5) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2) & (grp_fu_1107_p2 == 1'd1)) | ((state_read_reg_1215 == 5'd7) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2) & (grp_fu_1107_p2 == 1'd1)) | ((state_read_read_fu_118_p2 == 5'd6) & (1'b1 == ap_ce) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)) | ((state_read_read_fu_118_p2 == 5'd0) & (1'b1 == ap_ce) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)) | ((state_read_read_fu_118_p2 == 5'd2) & (1'b1 == ap_ce) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)) | ((state_read_read_fu_118_p2 == 5'd4) & (1'b1 == ap_ce) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        HammingTable_hammingDistances_finalStates_we0 = 1'b1;
    end else begin
        HammingTable_hammingDistances_finalStates_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2) & (grp_fu_1113_p2 == 1'd1) & (state_read_reg_1215 == 5'd1)) | ((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2) & (grp_fu_1113_p2 == 1'd1) & (state_read_reg_1215 == 5'd3)) | ((state_read_reg_1215 == 5'd5) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2) & (grp_fu_1113_p2 == 1'd1)) | ((state_read_reg_1215 == 5'd7) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2) & (grp_fu_1113_p2 == 1'd1)) | ((state_read_read_fu_118_p2 == 5'd6) & (1'b1 == ap_ce) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)) | ((state_read_read_fu_118_p2 == 5'd0) & (1'b1 == ap_ce) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)) | ((state_read_read_fu_118_p2 == 5'd2) & (1'b1 == ap_ce) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)) | ((state_read_read_fu_118_p2 == 5'd4) & (1'b1 == ap_ce) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        HammingTable_hammingDistances_finalStates_we1 = 1'b1;
    end else begin
        HammingTable_hammingDistances_finalStates_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) | ((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state2) & (grp_fu_1113_p2 == 1'd1) & (state_read_reg_1215 == 5'd3)) | ((grp_fu_1113_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2) & (state_read_reg_1215 == 5'd3)) | ((state_read_reg_1215 == 5'd5) & (1'b1 == ap_CS_fsm_state2) & (grp_fu_1113_p2 == 1'd1)) | ((state_read_reg_1215 == 5'd5) & (grp_fu_1113_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)) | ((state_read_reg_1215 == 5'd7) & (1'b1 == ap_CS_fsm_state2) & (grp_fu_1113_p2 == 1'd1)) | ((state_read_reg_1215 == 5'd7) & (grp_fu_1113_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)))) begin
        ap_phi_mux_HammingTable_aTransi_30_phi_fu_1003_p26 = p_read221_reg_1444;
    end else if ((((1'b1 == ap_CS_fsm_state2) & (grp_fu_1113_p2 == 1'd1) & (state_read_reg_1215 == 5'd1)) | ((grp_fu_1113_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2) & (state_read_reg_1215 == 5'd1)))) begin
        ap_phi_mux_HammingTable_aTransi_30_phi_fu_1003_p26 = ap_phi_mux_HammingTable_aTransi_phi_fu_506_p4;
    end else begin
        ap_phi_mux_HammingTable_aTransi_30_phi_fu_1003_p26 = HammingTable_aTransi_30_reg_1000;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (state_read_reg_1215 == 5'd1))) begin
        if ((grp_fu_1107_p2 == 1'd0)) begin
            ap_phi_mux_HammingTable_aTransi_phi_fu_506_p4 = p_read221_reg_1444;
        end else if ((grp_fu_1107_p2 == 1'd1)) begin
            ap_phi_mux_HammingTable_aTransi_phi_fu_506_p4 = 8'd255;
        end else begin
            ap_phi_mux_HammingTable_aTransi_phi_fu_506_p4 = 'bx;
        end
    end else begin
        ap_phi_mux_HammingTable_aTransi_phi_fu_506_p4 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state2) & (grp_fu_1113_p2 == 1'd1) & (state_read_reg_1215 == 5'd3)) | ((grp_fu_1113_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2) & (state_read_reg_1215 == 5'd3)) | ((state_read_reg_1215 == 5'd5) & (1'b1 == ap_CS_fsm_state2) & (grp_fu_1113_p2 == 1'd1)) | ((state_read_reg_1215 == 5'd5) & (grp_fu_1113_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)) | ((state_read_reg_1215 == 5'd7) & (1'b1 == ap_CS_fsm_state2) & (grp_fu_1113_p2 == 1'd1)) | ((state_read_reg_1215 == 5'd7) & (grp_fu_1113_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)))) begin
        ap_phi_mux_HammingTable_bTransi_20_phi_fu_743_p26 = p_read423_reg_1414;
    end else if ((((1'b1 == ap_CS_fsm_state2) & (grp_fu_1113_p2 == 1'd1) & (state_read_reg_1215 == 5'd1)) | ((grp_fu_1113_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2) & (state_read_reg_1215 == 5'd1)))) begin
        ap_phi_mux_HammingTable_bTransi_20_phi_fu_743_p26 = ap_phi_mux_HammingTable_bTransi_phi_fu_496_p4;
    end else begin
        ap_phi_mux_HammingTable_bTransi_20_phi_fu_743_p26 = HammingTable_bTransi_20_reg_740;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (state_read_reg_1215 == 5'd1))) begin
        if ((grp_fu_1107_p2 == 1'd0)) begin
            ap_phi_mux_HammingTable_bTransi_phi_fu_496_p4 = 8'd255;
        end else if ((grp_fu_1107_p2 == 1'd1)) begin
            ap_phi_mux_HammingTable_bTransi_phi_fu_496_p4 = reg_1081;
        end else begin
            ap_phi_mux_HammingTable_bTransi_phi_fu_496_p4 = 'bx;
        end
    end else begin
        ap_phi_mux_HammingTable_bTransi_phi_fu_496_p4 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state2) & (grp_fu_1113_p2 == 1'd1) & (state_read_reg_1215 == 5'd3)) | ((grp_fu_1113_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2) & (state_read_reg_1215 == 5'd3)))) begin
        ap_phi_mux_HammingTable_cTransi_30_phi_fu_516_p26 = ap_phi_mux_HammingTable_cTransi_phi_fu_476_p4;
    end else if ((((1'b1 == ap_CS_fsm_state2) & (grp_fu_1113_p2 == 1'd1) & (state_read_reg_1215 == 5'd1)) | ((grp_fu_1113_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2) & (state_read_reg_1215 == 5'd1)) | ((state_read_reg_1215 == 5'd5) & (1'b1 == ap_CS_fsm_state2) & (grp_fu_1113_p2 == 1'd1)) | ((state_read_reg_1215 == 5'd5) & (grp_fu_1113_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)) | ((state_read_reg_1215 == 5'd7) & (1'b1 == ap_CS_fsm_state2) & (grp_fu_1113_p2 == 1'd1)) | ((state_read_reg_1215 == 5'd7) & (grp_fu_1113_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)))) begin
        ap_phi_mux_HammingTable_cTransi_30_phi_fu_516_p26 = p_read625_reg_1384;
    end else begin
        ap_phi_mux_HammingTable_cTransi_30_phi_fu_516_p26 = HammingTable_cTransi_30_reg_513;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (state_read_reg_1215 == 5'd3))) begin
        if ((grp_fu_1107_p2 == 1'd0)) begin
            ap_phi_mux_HammingTable_cTransi_phi_fu_476_p4 = p_read625_reg_1384;
        end else if ((grp_fu_1107_p2 == 1'd1)) begin
            ap_phi_mux_HammingTable_cTransi_phi_fu_476_p4 = 8'd255;
        end else begin
            ap_phi_mux_HammingTable_cTransi_phi_fu_476_p4 = 'bx;
        end
    end else begin
        ap_phi_mux_HammingTable_cTransi_phi_fu_476_p4 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state2) & (grp_fu_1113_p2 == 1'd1) & (state_read_reg_1215 == 5'd3)) | ((grp_fu_1113_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2) & (state_read_reg_1215 == 5'd3)))) begin
        ap_phi_mux_HammingTable_dTransi_20_phi_fu_581_p26 = ap_phi_mux_HammingTable_dTransi_phi_fu_486_p4;
    end else if ((((1'b1 == ap_CS_fsm_state2) & (grp_fu_1113_p2 == 1'd1) & (state_read_reg_1215 == 5'd1)) | ((grp_fu_1113_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2) & (state_read_reg_1215 == 5'd1)) | ((state_read_reg_1215 == 5'd5) & (1'b1 == ap_CS_fsm_state2) & (grp_fu_1113_p2 == 1'd1)) | ((state_read_reg_1215 == 5'd5) & (grp_fu_1113_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)) | ((state_read_reg_1215 == 5'd7) & (1'b1 == ap_CS_fsm_state2) & (grp_fu_1113_p2 == 1'd1)) | ((state_read_reg_1215 == 5'd7) & (grp_fu_1113_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)))) begin
        ap_phi_mux_HammingTable_dTransi_20_phi_fu_581_p26 = p_read827_reg_1354;
    end else begin
        ap_phi_mux_HammingTable_dTransi_20_phi_fu_581_p26 = HammingTable_dTransi_20_reg_578;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (state_read_reg_1215 == 5'd3))) begin
        if ((grp_fu_1107_p2 == 1'd0)) begin
            ap_phi_mux_HammingTable_dTransi_phi_fu_486_p4 = 8'd255;
        end else if ((grp_fu_1107_p2 == 1'd1)) begin
            ap_phi_mux_HammingTable_dTransi_phi_fu_486_p4 = reg_1081;
        end else begin
            ap_phi_mux_HammingTable_dTransi_phi_fu_486_p4 = 'bx;
        end
    end else begin
        ap_phi_mux_HammingTable_dTransi_phi_fu_486_p4 = 'bx;
    end
end

always @ (*) begin
    if ((((state_read_reg_1215 == 5'd5) & (1'b1 == ap_CS_fsm_state2) & (grp_fu_1113_p2 == 1'd1)) | ((state_read_reg_1215 == 5'd5) & (grp_fu_1113_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)))) begin
        ap_phi_mux_HammingTable_eTransi_30_phi_fu_678_p26 = ap_phi_mux_HammingTable_eTransi_phi_fu_456_p4;
    end else if ((((1'b1 == ap_CS_fsm_state2) & (grp_fu_1113_p2 == 1'd1) & (state_read_reg_1215 == 5'd1)) | ((grp_fu_1113_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2) & (state_read_reg_1215 == 5'd1)) | ((1'b1 == ap_CS_fsm_state2) & (grp_fu_1113_p2 == 1'd1) & (state_read_reg_1215 == 5'd3)) | ((grp_fu_1113_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2) & (state_read_reg_1215 == 5'd3)) | ((state_read_reg_1215 == 5'd7) & (1'b1 == ap_CS_fsm_state2) & (grp_fu_1113_p2 == 1'd1)) | ((state_read_reg_1215 == 5'd7) & (grp_fu_1113_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)))) begin
        ap_phi_mux_HammingTable_eTransi_30_phi_fu_678_p26 = p_read1029_reg_1324;
    end else begin
        ap_phi_mux_HammingTable_eTransi_30_phi_fu_678_p26 = HammingTable_eTransi_30_reg_675;
    end
end

always @ (*) begin
    if (((state_read_reg_1215 == 5'd5) & (1'b1 == ap_CS_fsm_state2))) begin
        if ((grp_fu_1107_p2 == 1'd0)) begin
            ap_phi_mux_HammingTable_eTransi_phi_fu_456_p4 = p_read1029_reg_1324;
        end else if ((grp_fu_1107_p2 == 1'd1)) begin
            ap_phi_mux_HammingTable_eTransi_phi_fu_456_p4 = 8'd255;
        end else begin
            ap_phi_mux_HammingTable_eTransi_phi_fu_456_p4 = 'bx;
        end
    end else begin
        ap_phi_mux_HammingTable_eTransi_phi_fu_456_p4 = 'bx;
    end
end

always @ (*) begin
    if ((((state_read_reg_1215 == 5'd5) & (1'b1 == ap_CS_fsm_state2) & (grp_fu_1113_p2 == 1'd1)) | ((state_read_reg_1215 == 5'd5) & (grp_fu_1113_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)))) begin
        ap_phi_mux_HammingTable_fTransi_20_phi_fu_776_p26 = ap_phi_mux_HammingTable_fTransi_phi_fu_466_p4;
    end else if ((((1'b1 == ap_CS_fsm_state2) & (grp_fu_1113_p2 == 1'd1) & (state_read_reg_1215 == 5'd1)) | ((grp_fu_1113_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2) & (state_read_reg_1215 == 5'd1)) | ((1'b1 == ap_CS_fsm_state2) & (grp_fu_1113_p2 == 1'd1) & (state_read_reg_1215 == 5'd3)) | ((grp_fu_1113_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2) & (state_read_reg_1215 == 5'd3)) | ((state_read_reg_1215 == 5'd7) & (1'b1 == ap_CS_fsm_state2) & (grp_fu_1113_p2 == 1'd1)) | ((state_read_reg_1215 == 5'd7) & (grp_fu_1113_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)))) begin
        ap_phi_mux_HammingTable_fTransi_20_phi_fu_776_p26 = p_read_31_reg_1294;
    end else begin
        ap_phi_mux_HammingTable_fTransi_20_phi_fu_776_p26 = HammingTable_fTransi_20_reg_773;
    end
end

always @ (*) begin
    if (((state_read_reg_1215 == 5'd5) & (1'b1 == ap_CS_fsm_state2))) begin
        if ((grp_fu_1107_p2 == 1'd0)) begin
            ap_phi_mux_HammingTable_fTransi_phi_fu_466_p4 = 8'd255;
        end else if ((grp_fu_1107_p2 == 1'd1)) begin
            ap_phi_mux_HammingTable_fTransi_phi_fu_466_p4 = reg_1081;
        end else begin
            ap_phi_mux_HammingTable_fTransi_phi_fu_466_p4 = 'bx;
        end
    end else begin
        ap_phi_mux_HammingTable_fTransi_phi_fu_466_p4 = 'bx;
    end
end

always @ (*) begin
    if ((((state_read_reg_1215 == 5'd7) & (1'b1 == ap_CS_fsm_state2) & (grp_fu_1113_p2 == 1'd1)) | ((state_read_reg_1215 == 5'd7) & (grp_fu_1113_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)))) begin
        ap_phi_mux_HammingTable_gTransi_30_phi_fu_841_p26 = ap_phi_mux_HammingTable_gTransi_phi_fu_436_p4;
    end else if ((((1'b1 == ap_CS_fsm_state2) & (grp_fu_1113_p2 == 1'd1) & (state_read_reg_1215 == 5'd1)) | ((grp_fu_1113_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2) & (state_read_reg_1215 == 5'd1)) | ((1'b1 == ap_CS_fsm_state2) & (grp_fu_1113_p2 == 1'd1) & (state_read_reg_1215 == 5'd3)) | ((grp_fu_1113_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2) & (state_read_reg_1215 == 5'd3)) | ((state_read_reg_1215 == 5'd5) & (1'b1 == ap_CS_fsm_state2) & (grp_fu_1113_p2 == 1'd1)) | ((state_read_reg_1215 == 5'd5) & (grp_fu_1113_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)))) begin
        ap_phi_mux_HammingTable_gTransi_30_phi_fu_841_p26 = p_read_29_reg_1264;
    end else begin
        ap_phi_mux_HammingTable_gTransi_30_phi_fu_841_p26 = HammingTable_gTransi_30_reg_838;
    end
end

always @ (*) begin
    if (((state_read_reg_1215 == 5'd7) & (1'b1 == ap_CS_fsm_state2))) begin
        if ((grp_fu_1107_p2 == 1'd0)) begin
            ap_phi_mux_HammingTable_gTransi_phi_fu_436_p4 = p_read_29_reg_1264;
        end else if ((grp_fu_1107_p2 == 1'd1)) begin
            ap_phi_mux_HammingTable_gTransi_phi_fu_436_p4 = 8'd255;
        end else begin
            ap_phi_mux_HammingTable_gTransi_phi_fu_436_p4 = 'bx;
        end
    end else begin
        ap_phi_mux_HammingTable_gTransi_phi_fu_436_p4 = 'bx;
    end
end

always @ (*) begin
    if ((((state_read_reg_1215 == 5'd7) & (1'b1 == ap_CS_fsm_state2) & (grp_fu_1113_p2 == 1'd1)) | ((state_read_reg_1215 == 5'd7) & (grp_fu_1113_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)))) begin
        ap_phi_mux_HammingTable_hTransi_20_phi_fu_938_p26 = ap_phi_mux_HammingTable_hTransi_phi_fu_446_p4;
    end else if ((((1'b1 == ap_CS_fsm_state2) & (grp_fu_1113_p2 == 1'd1) & (state_read_reg_1215 == 5'd1)) | ((grp_fu_1113_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2) & (state_read_reg_1215 == 5'd1)) | ((1'b1 == ap_CS_fsm_state2) & (grp_fu_1113_p2 == 1'd1) & (state_read_reg_1215 == 5'd3)) | ((grp_fu_1113_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2) & (state_read_reg_1215 == 5'd3)) | ((state_read_reg_1215 == 5'd5) & (1'b1 == ap_CS_fsm_state2) & (grp_fu_1113_p2 == 1'd1)) | ((state_read_reg_1215 == 5'd5) & (grp_fu_1113_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)))) begin
        ap_phi_mux_HammingTable_hTransi_20_phi_fu_938_p26 = p_read_27_reg_1234;
    end else begin
        ap_phi_mux_HammingTable_hTransi_20_phi_fu_938_p26 = HammingTable_hTransi_20_reg_935;
    end
end

always @ (*) begin
    if (((state_read_reg_1215 == 5'd7) & (1'b1 == ap_CS_fsm_state2))) begin
        if ((grp_fu_1107_p2 == 1'd0)) begin
            ap_phi_mux_HammingTable_hTransi_phi_fu_446_p4 = 8'd255;
        end else if ((grp_fu_1107_p2 == 1'd1)) begin
            ap_phi_mux_HammingTable_hTransi_phi_fu_446_p4 = reg_1081;
        end else begin
            ap_phi_mux_HammingTable_hTransi_phi_fu_446_p4 = 'bx;
        end
    end else begin
        ap_phi_mux_HammingTable_hTransi_phi_fu_446_p4 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (grp_fu_1113_p2 == 1'd1) & (state_read_reg_1215 == 5'd3))) begin
        ap_phi_mux_phi_ln228_1_phi_fu_614_p26 = reg_1094;
    end else if (((grp_fu_1113_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2) & (state_read_reg_1215 == 5'd3))) begin
        ap_phi_mux_phi_ln228_1_phi_fu_614_p26 = 8'd255;
    end else if ((((1'b1 == ap_CS_fsm_state2) & (grp_fu_1113_p2 == 1'd1) & (state_read_reg_1215 == 5'd1)) | ((grp_fu_1113_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2) & (state_read_reg_1215 == 5'd1)) | ((state_read_reg_1215 == 5'd5) & (1'b1 == ap_CS_fsm_state2) & (grp_fu_1113_p2 == 1'd1)) | ((state_read_reg_1215 == 5'd5) & (grp_fu_1113_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)) | ((state_read_reg_1215 == 5'd7) & (1'b1 == ap_CS_fsm_state2) & (grp_fu_1113_p2 == 1'd1)) | ((state_read_reg_1215 == 5'd7) & (grp_fu_1113_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)))) begin
        ap_phi_mux_phi_ln228_1_phi_fu_614_p26 = p_read928_reg_1339;
    end else begin
        ap_phi_mux_phi_ln228_1_phi_fu_614_p26 = phi_ln228_1_reg_611;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state2) & (grp_fu_1113_p2 == 1'd1) & (state_read_reg_1215 == 5'd3)) | ((grp_fu_1113_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2) & (state_read_reg_1215 == 5'd3)) | ((state_read_reg_1215 == 5'd5) & (1'b1 == ap_CS_fsm_state2) & (grp_fu_1113_p2 == 1'd1)) | ((state_read_reg_1215 == 5'd5) & (grp_fu_1113_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)) | ((state_read_reg_1215 == 5'd7) & (1'b1 == ap_CS_fsm_state2) & (grp_fu_1113_p2 == 1'd1)) | ((state_read_reg_1215 == 5'd7) & (grp_fu_1113_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)))) begin
        ap_phi_mux_phi_ln228_2_phi_fu_646_p26 = p_read524_reg_1399;
    end else if (((1'b1 == ap_CS_fsm_state2) & (grp_fu_1113_p2 == 1'd1) & (state_read_reg_1215 == 5'd1))) begin
        ap_phi_mux_phi_ln228_2_phi_fu_646_p26 = reg_1094;
    end else if (((grp_fu_1113_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2) & (state_read_reg_1215 == 5'd1))) begin
        ap_phi_mux_phi_ln228_2_phi_fu_646_p26 = 8'd255;
    end else begin
        ap_phi_mux_phi_ln228_2_phi_fu_646_p26 = phi_ln228_2_reg_643;
    end
end

always @ (*) begin
    if (((state_read_reg_1215 == 5'd5) & (1'b1 == ap_CS_fsm_state2) & (grp_fu_1113_p2 == 1'd1))) begin
        ap_phi_mux_phi_ln228_3_phi_fu_711_p26 = 8'd255;
    end else if ((((1'b1 == ap_CS_fsm_state2) & (grp_fu_1113_p2 == 1'd1) & (state_read_reg_1215 == 5'd1)) | ((grp_fu_1113_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2) & (state_read_reg_1215 == 5'd1)) | ((1'b1 == ap_CS_fsm_state2) & (grp_fu_1113_p2 == 1'd1) & (state_read_reg_1215 == 5'd3)) | ((grp_fu_1113_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2) & (state_read_reg_1215 == 5'd3)) | ((state_read_reg_1215 == 5'd5) & (grp_fu_1113_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)) | ((state_read_reg_1215 == 5'd7) & (1'b1 == ap_CS_fsm_state2) & (grp_fu_1113_p2 == 1'd1)) | ((state_read_reg_1215 == 5'd7) & (grp_fu_1113_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)))) begin
        ap_phi_mux_phi_ln228_3_phi_fu_711_p26 = p_read_32_reg_1309;
    end else begin
        ap_phi_mux_phi_ln228_3_phi_fu_711_p26 = phi_ln228_3_reg_708;
    end
end

always @ (*) begin
    if (((state_read_reg_1215 == 5'd5) & (1'b1 == ap_CS_fsm_state2) & (grp_fu_1113_p2 == 1'd1))) begin
        ap_phi_mux_phi_ln228_4_phi_fu_809_p26 = reg_1094;
    end else if (((state_read_reg_1215 == 5'd5) & (grp_fu_1113_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_phi_mux_phi_ln228_4_phi_fu_809_p26 = 8'd255;
    end else if ((((1'b1 == ap_CS_fsm_state2) & (grp_fu_1113_p2 == 1'd1) & (state_read_reg_1215 == 5'd1)) | ((grp_fu_1113_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2) & (state_read_reg_1215 == 5'd1)) | ((1'b1 == ap_CS_fsm_state2) & (grp_fu_1113_p2 == 1'd1) & (state_read_reg_1215 == 5'd3)) | ((grp_fu_1113_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2) & (state_read_reg_1215 == 5'd3)) | ((state_read_reg_1215 == 5'd7) & (1'b1 == ap_CS_fsm_state2) & (grp_fu_1113_p2 == 1'd1)) | ((state_read_reg_1215 == 5'd7) & (grp_fu_1113_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)))) begin
        ap_phi_mux_phi_ln228_4_phi_fu_809_p26 = p_read_30_reg_1279;
    end else begin
        ap_phi_mux_phi_ln228_4_phi_fu_809_p26 = phi_ln228_4_reg_806;
    end
end

always @ (*) begin
    if (((state_read_reg_1215 == 5'd7) & (1'b1 == ap_CS_fsm_state2) & (grp_fu_1113_p2 == 1'd1))) begin
        ap_phi_mux_phi_ln228_5_phi_fu_874_p26 = 8'd255;
    end else if ((((1'b1 == ap_CS_fsm_state2) & (grp_fu_1113_p2 == 1'd1) & (state_read_reg_1215 == 5'd1)) | ((grp_fu_1113_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2) & (state_read_reg_1215 == 5'd1)) | ((1'b1 == ap_CS_fsm_state2) & (grp_fu_1113_p2 == 1'd1) & (state_read_reg_1215 == 5'd3)) | ((grp_fu_1113_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2) & (state_read_reg_1215 == 5'd3)) | ((state_read_reg_1215 == 5'd5) & (1'b1 == ap_CS_fsm_state2) & (grp_fu_1113_p2 == 1'd1)) | ((state_read_reg_1215 == 5'd5) & (grp_fu_1113_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)) | ((state_read_reg_1215 == 5'd7) & (grp_fu_1113_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)))) begin
        ap_phi_mux_phi_ln228_5_phi_fu_874_p26 = p_read_28_reg_1249;
    end else begin
        ap_phi_mux_phi_ln228_5_phi_fu_874_p26 = phi_ln228_5_reg_871;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (grp_fu_1113_p2 == 1'd1) & (state_read_reg_1215 == 5'd1))) begin
        ap_phi_mux_phi_ln228_6_phi_fu_906_p26 = 8'd255;
    end else if ((((grp_fu_1113_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2) & (state_read_reg_1215 == 5'd1)) | ((1'b1 == ap_CS_fsm_state2) & (grp_fu_1113_p2 == 1'd1) & (state_read_reg_1215 == 5'd3)) | ((grp_fu_1113_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2) & (state_read_reg_1215 == 5'd3)) | ((state_read_reg_1215 == 5'd5) & (1'b1 == ap_CS_fsm_state2) & (grp_fu_1113_p2 == 1'd1)) | ((state_read_reg_1215 == 5'd5) & (grp_fu_1113_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)) | ((state_read_reg_1215 == 5'd7) & (1'b1 == ap_CS_fsm_state2) & (grp_fu_1113_p2 == 1'd1)) | ((state_read_reg_1215 == 5'd7) & (grp_fu_1113_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)))) begin
        ap_phi_mux_phi_ln228_6_phi_fu_906_p26 = p_read322_reg_1429;
    end else begin
        ap_phi_mux_phi_ln228_6_phi_fu_906_p26 = phi_ln228_6_reg_903;
    end
end

always @ (*) begin
    if (((state_read_reg_1215 == 5'd7) & (1'b1 == ap_CS_fsm_state2) & (grp_fu_1113_p2 == 1'd1))) begin
        ap_phi_mux_phi_ln228_7_phi_fu_971_p26 = reg_1094;
    end else if (((state_read_reg_1215 == 5'd7) & (grp_fu_1113_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_phi_mux_phi_ln228_7_phi_fu_971_p26 = 8'd255;
    end else if ((((1'b1 == ap_CS_fsm_state2) & (grp_fu_1113_p2 == 1'd1) & (state_read_reg_1215 == 5'd1)) | ((grp_fu_1113_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2) & (state_read_reg_1215 == 5'd1)) | ((1'b1 == ap_CS_fsm_state2) & (grp_fu_1113_p2 == 1'd1) & (state_read_reg_1215 == 5'd3)) | ((grp_fu_1113_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2) & (state_read_reg_1215 == 5'd3)) | ((state_read_reg_1215 == 5'd5) & (1'b1 == ap_CS_fsm_state2) & (grp_fu_1113_p2 == 1'd1)) | ((state_read_reg_1215 == 5'd5) & (grp_fu_1113_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)))) begin
        ap_phi_mux_phi_ln228_7_phi_fu_971_p26 = p_read_26_reg_1219;
    end else begin
        ap_phi_mux_phi_ln228_7_phi_fu_971_p26 = phi_ln228_7_reg_968;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (grp_fu_1113_p2 == 1'd1) & (state_read_reg_1215 == 5'd3))) begin
        ap_phi_mux_phi_ln228_phi_fu_549_p26 = 8'd255;
    end else if ((((1'b1 == ap_CS_fsm_state2) & (grp_fu_1113_p2 == 1'd1) & (state_read_reg_1215 == 5'd1)) | ((grp_fu_1113_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2) & (state_read_reg_1215 == 5'd1)) | ((grp_fu_1113_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2) & (state_read_reg_1215 == 5'd3)) | ((state_read_reg_1215 == 5'd5) & (1'b1 == ap_CS_fsm_state2) & (grp_fu_1113_p2 == 1'd1)) | ((state_read_reg_1215 == 5'd5) & (grp_fu_1113_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)) | ((state_read_reg_1215 == 5'd7) & (1'b1 == ap_CS_fsm_state2) & (grp_fu_1113_p2 == 1'd1)) | ((state_read_reg_1215 == 5'd7) & (grp_fu_1113_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)))) begin
        ap_phi_mux_phi_ln228_phi_fu_549_p26 = p_read726_reg_1369;
    end else begin
        ap_phi_mux_phi_ln228_phi_fu_549_p26 = phi_ln228_reg_546;
    end
end

always @ (*) begin
    if (((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((((state_read_read_fu_118_p2 == 5'd5) & (1'b1 == ap_CS_fsm_state1)) | ((state_read_read_fu_118_p2 == 5'd6) & (1'b1 == ap_CS_fsm_state1)) | ((state_read_read_fu_118_p2 == 5'd0) & (1'b1 == ap_CS_fsm_state1)) | ((state_read_read_fu_118_p2 == 5'd3) & (1'b1 == ap_CS_fsm_state1)))) begin
        grp_calculateDistanceFor_fu_1033_firstBit = 1'd0;
    end else if ((((state_read_read_fu_118_p2 == 5'd7) & (1'b1 == ap_CS_fsm_state1)) | ((state_read_read_fu_118_p2 == 5'd1) & (1'b1 == ap_CS_fsm_state1)) | ((state_read_read_fu_118_p2 == 5'd2) & (1'b1 == ap_CS_fsm_state1)) | ((state_read_read_fu_118_p2 == 5'd4) & (1'b1 == ap_CS_fsm_state1)))) begin
        grp_calculateDistanceFor_fu_1033_firstBit = 1'd1;
    end else begin
        grp_calculateDistanceFor_fu_1033_firstBit = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        if ((state_read_read_fu_118_p2 == 5'd0)) begin
            grp_calculateDistanceFor_fu_1033_previousDistance = p_read18;
        end else if ((state_read_read_fu_118_p2 == 5'd1)) begin
            grp_calculateDistanceFor_fu_1033_previousDistance = p_read31;
        end else if ((state_read_read_fu_118_p2 == 5'd2)) begin
            grp_calculateDistanceFor_fu_1033_previousDistance = p_read32;
        end else if ((state_read_read_fu_118_p2 == 5'd3)) begin
            grp_calculateDistanceFor_fu_1033_previousDistance = p_read33;
        end else if ((state_read_read_fu_118_p2 == 5'd4)) begin
            grp_calculateDistanceFor_fu_1033_previousDistance = p_read34;
        end else if ((state_read_read_fu_118_p2 == 5'd5)) begin
            grp_calculateDistanceFor_fu_1033_previousDistance = p_read35;
        end else if ((state_read_read_fu_118_p2 == 5'd6)) begin
            grp_calculateDistanceFor_fu_1033_previousDistance = p_read36;
        end else if ((state_read_read_fu_118_p2 == 5'd7)) begin
            grp_calculateDistanceFor_fu_1033_previousDistance = p_read37;
        end else begin
            grp_calculateDistanceFor_fu_1033_previousDistance = 'bx;
        end
    end else begin
        grp_calculateDistanceFor_fu_1033_previousDistance = 'bx;
    end
end

always @ (*) begin
    if ((((state_read_read_fu_118_p2 == 5'd6) & (1'b1 == ap_CS_fsm_state1)) | ((state_read_read_fu_118_p2 == 5'd1) & (1'b1 == ap_CS_fsm_state1)) | ((state_read_read_fu_118_p2 == 5'd3) & (1'b1 == ap_CS_fsm_state1)) | ((state_read_read_fu_118_p2 == 5'd4) & (1'b1 == ap_CS_fsm_state1)))) begin
        grp_calculateDistanceFor_fu_1033_secondBit = 1'd1;
    end else if ((((state_read_read_fu_118_p2 == 5'd5) & (1'b1 == ap_CS_fsm_state1)) | ((state_read_read_fu_118_p2 == 5'd7) & (1'b1 == ap_CS_fsm_state1)) | ((state_read_read_fu_118_p2 == 5'd0) & (1'b1 == ap_CS_fsm_state1)) | ((state_read_read_fu_118_p2 == 5'd2) & (1'b1 == ap_CS_fsm_state1)))) begin
        grp_calculateDistanceFor_fu_1033_secondBit = 1'd0;
    end else begin
        grp_calculateDistanceFor_fu_1033_secondBit = 'bx;
    end
end

always @ (*) begin
    if ((((state_read_read_fu_118_p2 == 5'd5) & (1'b1 == ap_CS_fsm_state1)) | ((state_read_read_fu_118_p2 == 5'd6) & (1'b1 == ap_CS_fsm_state1)) | ((state_read_read_fu_118_p2 == 5'd0) & (1'b1 == ap_CS_fsm_state1)) | ((state_read_read_fu_118_p2 == 5'd3) & (1'b1 == ap_CS_fsm_state1)))) begin
        grp_calculateDistanceFor_fu_1047_firstBit = 1'd1;
    end else if ((((state_read_read_fu_118_p2 == 5'd7) & (1'b1 == ap_CS_fsm_state1)) | ((state_read_read_fu_118_p2 == 5'd1) & (1'b1 == ap_CS_fsm_state1)) | ((state_read_read_fu_118_p2 == 5'd2) & (1'b1 == ap_CS_fsm_state1)) | ((state_read_read_fu_118_p2 == 5'd4) & (1'b1 == ap_CS_fsm_state1)))) begin
        grp_calculateDistanceFor_fu_1047_firstBit = 1'd0;
    end else begin
        grp_calculateDistanceFor_fu_1047_firstBit = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        if ((state_read_read_fu_118_p2 == 5'd0)) begin
            grp_calculateDistanceFor_fu_1047_previousDistance = p_read18;
        end else if ((state_read_read_fu_118_p2 == 5'd1)) begin
            grp_calculateDistanceFor_fu_1047_previousDistance = p_read31;
        end else if ((state_read_read_fu_118_p2 == 5'd2)) begin
            grp_calculateDistanceFor_fu_1047_previousDistance = p_read32;
        end else if ((state_read_read_fu_118_p2 == 5'd3)) begin
            grp_calculateDistanceFor_fu_1047_previousDistance = p_read33;
        end else if ((state_read_read_fu_118_p2 == 5'd4)) begin
            grp_calculateDistanceFor_fu_1047_previousDistance = p_read34;
        end else if ((state_read_read_fu_118_p2 == 5'd5)) begin
            grp_calculateDistanceFor_fu_1047_previousDistance = p_read35;
        end else if ((state_read_read_fu_118_p2 == 5'd6)) begin
            grp_calculateDistanceFor_fu_1047_previousDistance = p_read36;
        end else if ((state_read_read_fu_118_p2 == 5'd7)) begin
            grp_calculateDistanceFor_fu_1047_previousDistance = p_read37;
        end else begin
            grp_calculateDistanceFor_fu_1047_previousDistance = 'bx;
        end
    end else begin
        grp_calculateDistanceFor_fu_1047_previousDistance = 'bx;
    end
end

always @ (*) begin
    if ((((state_read_read_fu_118_p2 == 5'd6) & (1'b1 == ap_CS_fsm_state1)) | ((state_read_read_fu_118_p2 == 5'd1) & (1'b1 == ap_CS_fsm_state1)) | ((state_read_read_fu_118_p2 == 5'd3) & (1'b1 == ap_CS_fsm_state1)) | ((state_read_read_fu_118_p2 == 5'd4) & (1'b1 == ap_CS_fsm_state1)))) begin
        grp_calculateDistanceFor_fu_1047_secondBit = 1'd0;
    end else if ((((state_read_read_fu_118_p2 == 5'd5) & (1'b1 == ap_CS_fsm_state1)) | ((state_read_read_fu_118_p2 == 5'd7) & (1'b1 == ap_CS_fsm_state1)) | ((state_read_read_fu_118_p2 == 5'd0) & (1'b1 == ap_CS_fsm_state1)) | ((state_read_read_fu_118_p2 == 5'd2) & (1'b1 == ap_CS_fsm_state1)))) begin
        grp_calculateDistanceFor_fu_1047_secondBit = 1'd1;
    end else begin
        grp_calculateDistanceFor_fu_1047_secondBit = 'bx;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_ce) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign HammingTable_hamming_42_gep_fu_424_p3 = 64'd4;

assign HammingTable_hamming_43_reg_1489 = 64'd0;

assign HammingTable_hamming_45_reg_1494 = 64'd4;

assign HammingTable_hamming_47_gep_fu_379_p3 = 64'd1;

assign HammingTable_hamming_48_gep_fu_388_p3 = 64'd5;

assign HammingTable_hamming_49_reg_1479 = 64'd1;

assign HammingTable_hamming_51_reg_1484 = 64'd5;

assign HammingTable_hamming_53_gep_fu_343_p3 = 64'd2;

assign HammingTable_hamming_54_gep_fu_352_p3 = 64'd6;

assign HammingTable_hamming_55_reg_1469 = 64'd2;

assign HammingTable_hamming_57_reg_1474 = 64'd6;

assign HammingTable_hamming_59_gep_fu_307_p3 = 64'd3;

assign HammingTable_hamming_60_gep_fu_316_p3 = 64'd7;

assign HammingTable_hamming_61_reg_1459 = 64'd3;

assign HammingTable_hamming_63_reg_1464 = 64'd7;

assign HammingTable_hamming_gep_fu_415_p3 = 64'd0;

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_return_0 = ap_phi_mux_HammingTable_aTransi_30_phi_fu_1003_p26;

assign ap_return_1 = ap_phi_mux_phi_ln228_6_phi_fu_906_p26;

assign ap_return_10 = ap_phi_mux_HammingTable_fTransi_20_phi_fu_776_p26;

assign ap_return_11 = ap_phi_mux_phi_ln228_4_phi_fu_809_p26;

assign ap_return_12 = ap_phi_mux_HammingTable_gTransi_30_phi_fu_841_p26;

assign ap_return_13 = ap_phi_mux_phi_ln228_5_phi_fu_874_p26;

assign ap_return_14 = ap_phi_mux_HammingTable_hTransi_20_phi_fu_938_p26;

assign ap_return_15 = ap_phi_mux_phi_ln228_7_phi_fu_971_p26;

assign ap_return_2 = ap_phi_mux_HammingTable_bTransi_20_phi_fu_743_p26;

assign ap_return_3 = ap_phi_mux_phi_ln228_2_phi_fu_646_p26;

assign ap_return_4 = ap_phi_mux_HammingTable_cTransi_30_phi_fu_516_p26;

assign ap_return_5 = ap_phi_mux_phi_ln228_phi_fu_549_p26;

assign ap_return_6 = ap_phi_mux_HammingTable_dTransi_20_phi_fu_581_p26;

assign ap_return_7 = ap_phi_mux_phi_ln228_1_phi_fu_614_p26;

assign ap_return_8 = ap_phi_mux_HammingTable_eTransi_30_phi_fu_678_p26;

assign ap_return_9 = ap_phi_mux_phi_ln228_3_phi_fu_711_p26;

assign grp_fu_1107_p2 = (($signed(reg_1081) < $signed(HammingTable_hammingDistances_finalStates_q0)) ? 1'b1 : 1'b0);

assign grp_fu_1113_p2 = (($signed(reg_1094) < $signed(HammingTable_hammingDistances_finalStates_q1)) ? 1'b1 : 1'b0);

assign state_read_read_fu_118_p2 = state;

endmodule //calculateForState
