// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module getReturnPath (
        ap_ready,
        p_read,
        p_read1,
        p_read2,
        p_read3,
        p_read4,
        p_read5,
        p_read6,
        p_read7,
        state,
        ap_return
);


output   ap_ready;
input  [7:0] p_read;
input  [7:0] p_read1;
input  [7:0] p_read2;
input  [7:0] p_read3;
input  [7:0] p_read4;
input  [7:0] p_read5;
input  [7:0] p_read6;
input  [7:0] p_read7;
input  [2:0] state;
output  [2:0] ap_return;

wire   [0:0] icmp_ln296_fu_110_p2;
wire   [0:0] icmp_ln304_fu_120_p2;
wire   [0:0] icmp_ln312_fu_134_p2;
wire   [0:0] icmp_ln321_fu_148_p2;
wire   [0:0] icmp_ln330_fu_162_p2;
wire   [0:0] icmp_ln339_fu_172_p2;
wire   [0:0] icmp_ln348_fu_186_p2;
wire   [0:0] icmp_ln357_fu_200_p2;
wire   [0:0] icmp_ln294_fu_214_p2;
wire   [1:0] select_ln357_fu_206_p3;
wire   [1:0] select_ln294_fu_220_p3;
wire   [0:0] icmp_ln294_1_fu_232_p2;
wire   [2:0] select_ln348_fu_192_p3;
wire  signed [2:0] sext_ln294_fu_228_p1;
wire   [0:0] icmp_ln294_2_fu_246_p2;
wire   [2:0] select_ln339_fu_178_p3;
wire   [2:0] select_ln294_1_fu_238_p3;
wire   [0:0] icmp_ln294_3_fu_260_p2;
wire   [2:0] zext_ln339_fu_168_p1;
wire   [2:0] select_ln294_2_fu_252_p3;
wire   [0:0] icmp_ln294_4_fu_274_p2;
wire   [2:0] select_ln321_fu_154_p3;
wire   [2:0] select_ln294_3_fu_266_p3;
wire   [0:0] icmp_ln294_5_fu_288_p2;
wire   [2:0] select_ln312_fu_140_p3;
wire   [2:0] select_ln294_4_fu_280_p3;
wire   [0:0] icmp_ln294_6_fu_302_p2;
wire   [2:0] select_ln304_fu_126_p3;
wire   [2:0] select_ln294_5_fu_294_p3;
wire   [0:0] icmp_ln294_7_fu_316_p2;
wire   [2:0] zext_ln304_fu_116_p1;
wire   [2:0] select_ln294_6_fu_308_p3;

assign ap_ready = 1'b1;

assign ap_return = ((icmp_ln294_7_fu_316_p2[0:0] === 1'b1) ? zext_ln304_fu_116_p1 : select_ln294_6_fu_308_p3);

assign icmp_ln294_1_fu_232_p2 = ((state == 3'd6) ? 1'b1 : 1'b0);

assign icmp_ln294_2_fu_246_p2 = ((state == 3'd5) ? 1'b1 : 1'b0);

assign icmp_ln294_3_fu_260_p2 = ((state == 3'd4) ? 1'b1 : 1'b0);

assign icmp_ln294_4_fu_274_p2 = ((state == 3'd3) ? 1'b1 : 1'b0);

assign icmp_ln294_5_fu_288_p2 = ((state == 3'd2) ? 1'b1 : 1'b0);

assign icmp_ln294_6_fu_302_p2 = ((state == 3'd1) ? 1'b1 : 1'b0);

assign icmp_ln294_7_fu_316_p2 = ((state == 3'd0) ? 1'b1 : 1'b0);

assign icmp_ln294_fu_214_p2 = ((state == 3'd7) ? 1'b1 : 1'b0);

assign icmp_ln296_fu_110_p2 = ((p_read == 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln304_fu_120_p2 = ((p_read2 == 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln312_fu_134_p2 = ((p_read4 == 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln321_fu_148_p2 = ((p_read6 == 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln330_fu_162_p2 = ((p_read1 == 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln339_fu_172_p2 = ((p_read3 == 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln348_fu_186_p2 = ((p_read5 == 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln357_fu_200_p2 = ((p_read7 == 8'd255) ? 1'b1 : 1'b0);

assign select_ln294_1_fu_238_p3 = ((icmp_ln294_1_fu_232_p2[0:0] === 1'b1) ? select_ln348_fu_192_p3 : sext_ln294_fu_228_p1);

assign select_ln294_2_fu_252_p3 = ((icmp_ln294_2_fu_246_p2[0:0] === 1'b1) ? select_ln339_fu_178_p3 : select_ln294_1_fu_238_p3);

assign select_ln294_3_fu_266_p3 = ((icmp_ln294_3_fu_260_p2[0:0] === 1'b1) ? zext_ln339_fu_168_p1 : select_ln294_2_fu_252_p3);

assign select_ln294_4_fu_280_p3 = ((icmp_ln294_4_fu_274_p2[0:0] === 1'b1) ? select_ln321_fu_154_p3 : select_ln294_3_fu_266_p3);

assign select_ln294_5_fu_294_p3 = ((icmp_ln294_5_fu_288_p2[0:0] === 1'b1) ? select_ln312_fu_140_p3 : select_ln294_4_fu_280_p3);

assign select_ln294_6_fu_308_p3 = ((icmp_ln294_6_fu_302_p2[0:0] === 1'b1) ? select_ln304_fu_126_p3 : select_ln294_5_fu_294_p3);

assign select_ln294_fu_220_p3 = ((icmp_ln294_fu_214_p2[0:0] === 1'b1) ? select_ln357_fu_206_p3 : 2'd0);

assign select_ln304_fu_126_p3 = ((icmp_ln304_fu_120_p2[0:0] === 1'b1) ? 3'd3 : 3'd2);

assign select_ln312_fu_140_p3 = ((icmp_ln312_fu_134_p2[0:0] === 1'b1) ? 3'd5 : 3'd4);

assign select_ln321_fu_154_p3 = ((icmp_ln321_fu_148_p2[0:0] === 1'b1) ? 3'd7 : 3'd6);

assign select_ln339_fu_178_p3 = ((icmp_ln339_fu_172_p2[0:0] === 1'b1) ? 3'd3 : 3'd2);

assign select_ln348_fu_192_p3 = ((icmp_ln348_fu_186_p2[0:0] === 1'b1) ? 3'd5 : 3'd4);

assign select_ln357_fu_206_p3 = ((icmp_ln357_fu_200_p2[0:0] === 1'b1) ? 2'd3 : 2'd2);

assign sext_ln294_fu_228_p1 = $signed(select_ln294_fu_220_p3);

assign zext_ln304_fu_116_p1 = icmp_ln296_fu_110_p2;

assign zext_ln339_fu_168_p1 = icmp_ln330_fu_162_p2;

endmodule //getReturnPath
